import type {Gen} from '@ryanatkn/gro/gen.js';
import {z} from 'zod';

import {action_schemas_registry} from '$lib/schemas.js';
import {
	to_action_params_name,
	to_action_response_name,
	get_schema_imports,
	is_service_action,
	is_client_action,
} from '$lib/schema_helpers.js';
import {get_innermost_type} from '$lib/zod_helpers.js';

/**
 * Outputs a file with action types that can be imported from anywhere with no runtime cost.
 */
export const gen: Gen = ({origin_path}) => {
	// Get all schema names that need to be imported
	const schema_imports = get_schema_imports(action_schemas_registry);

	return `
// generated by ${origin_path}

import type {Api_Result} from '$lib/api.js';
import type {Service_Return, Non_Authenticated_Service, Non_Authorized_Service, Authorized_Service} from '$lib/server/service.js';
import type {Mutation} from '$lib/mutation.js';
import type {${schema_imports.join(', ')}} from '$lib/schemas.js';

/**
 * Names of all service actions
 */
export type Service_Action_Name = ${
		action_schemas_registry
			.filter(is_service_action)
			.map((schema) => `'${schema.name}'`)
			.join(' | ') || 'never'
	};

/**
 * Names of all client-only actions
 */
export type Client_Action_Name = ${
		action_schemas_registry
			.filter(is_client_action)
			.map((schema) => `'${schema.name}'`)
			.join(' | ') || 'never'
	};

/**
 * Maps action names to their parameter types
 */
export interface Action_Params_By_Name {
	${action_schemas_registry.map((schema) => `${schema.name}: ${to_action_params_name(schema.name)};`).join('\n\t')}
}

/**
 * Maps action names to their response types (server actions only)
 */
export interface Action_Response_By_Name {
	${action_schemas_registry
		.filter(is_service_action)
		.map((schema) => `${schema.name}: ${to_action_response_name(schema.name)};`)
		.join('\n\t')}
}

/**
 * Maps action names to their service implementations
 */
export interface Service_By_Name {
	${action_schemas_registry
		.filter(is_service_action)
		.map(
			(schema) =>
				`${schema.name}: Non_Authenticated_Service<${to_action_params_name(schema.name)}, Service_Return<${to_action_response_name(schema.name)}>>;`,
		)
		.join('\n\t')}
}

/**
 * Interface for action dispatch functions
 */
export interface Actions {
	${action_schemas_registry
		.map((schema) => {
			const hasParams = get_innermost_type(schema.params) !== z.ZodFirstPartyTypeKind.ZodNull;
			return `${schema.name}: (${hasParams ? `params: ${to_action_params_name(schema.name)}` : ''}) => Promise<${schema.returns}>;`;
		})
		.join('\n\t')}
}

/**
 * Interface for client-side mutation handlers
 */
export interface Mutations {
	[key: string]: Mutation | undefined;
	${action_schemas_registry
		.map((schema) => {
			const responseType = is_service_action(schema)
				? `Api_Result<${to_action_response_name(schema.name)}>`
				: 'void';
			return `${schema.name}?: Mutation<${to_action_params_name(schema.name)}, ${responseType}, ${schema.returns}>;`;
		})
		.join('\n\t')}
}

// generated by ${origin_path}
`.trim();
};
