import type {Gen} from '@ryanatkn/gro/gen.js';
import {z} from 'zod';

import {get_innermost_type_name} from '$lib/zod_helpers.js';
import {action_specs} from '$lib/action_collections.js';
import {Action_Registry} from '$lib/action_registry.js';
import {to_action_message_type} from '$lib/action_helpers.js';

/**
 * Outputs a file with generated types and schemas using the action specs as the source of truth.
 */
export const gen: Gen = ({origin_path}) => {
	const registry = new Action_Registry(action_specs);

	const banner = `generated by ${origin_path} - DO NOT EDIT OR RISK LOST DATA`;

	return `
		// ${banner}

		import {z} from 'zod';

		import type {Action_Inputs, Action_Outputs} from '$lib/action_collections.js';

		/**
		 * All action method names. Request/response actions have two types per method.
		 */
		export const Action_Method = z.enum([
			${registry.specs.map(({method}) => `'${method}'`).join(',\n\t')}
		]);
		export type Action_Method = z.infer<typeof Action_Method>;

		/**
		 * Names of all request_response actions.
		 */
		export type Request_Response_Action_Method = ${
			registry.request_response_specs.map((spec) => `'${spec.method}'`).join(' | ') || 'never'
		};

		/**
		 * Names of all remote_notification actions.
		 */
		export type Remote_Notification_Action_Method = ${
			registry.remote_notification_specs.map((spec) => `'${spec.method}'`).join(' | ') || 'never'
		};

		/**
		 * Names of all local_call actions.
		 */
		export type Local_Call_Action_Method = ${
			registry.local_call_specs.map((spec) => `'${spec.method}'`).join(' | ') || 'never'
		};

		/**
		 * All action types. May have '/' separators for namespacing.
		 * TODO maybe any relative url-encoded path is valid? add to schema defs
		 */
		export const Action_Message_Type = z.enum([
			${registry.specs
				.map((spec) =>
					spec.kind === 'request_response'
						? [
								`'${to_action_message_type(spec.method, 'request')}'`,
								`'${to_action_message_type(spec.method, 'response')}'`,
							]
						: `'${spec.method}'`,
				)
				.flat()
				.join(',\n\t')}
		]);
		export type Action_Message_Type = z.infer<typeof Action_Message_Type>;

		/**
		 * Interface for action dispatch functions.
		 */
		export interface Actions_Api {
			${registry.specs
				.map((spec) => {
					const innermost_type_name = get_innermost_type_name(spec.input);
					const has_input =
						innermost_type_name !== z.ZodFirstPartyTypeKind.ZodNull &&
						innermost_type_name !== z.ZodFirstPartyTypeKind.ZodVoid;
					return `${spec.method}: (${
						has_input
							? `input${spec.input.isOptional() ? '?' : ''}: Action_Inputs['${spec.method}']`
							: 'input?: void'
					}) => ${
						spec.kind === 'request_response'
							? `Promise<Action_Outputs['${spec.method}']>`
							: spec.kind === 'local_call'
								? spec.returns
								: 'void'
					};`;
				})
				.join('\n\t')}
		}

		// ${banner}
	`;
};
