import type {Gen} from '@ryanatkn/gro/gen.js';

import {
	to_action_spec_identifier,
	to_action_spec_params_identifier,
	to_action_spec_response_params_identifier,
	is_request_response_action,
} from '$lib/schema_helpers.js';
import {action_specs} from '$lib/action_collections.js';
import {Action_Registry} from '$lib/action_registry.js';

/**
 * Outputs a file with action schema definitions that can be imported by other modules.
 * This separates schema definitions from their usage in collections.
 */
export const gen: Gen = ({origin_path}) => {
	const registry = new Action_Registry(action_specs);

	const banner = `generated by ${origin_path} - DO NOT EDIT OR RISK LOST DATA`;

	return `
		// ${banner}

		import {z} from 'zod';
		
		import {Action_Message_Base} from '$lib/action_spec.js';
		import {${registry.specs
			// TODO maybe change to `import * as specs`
			.map((spec) => to_action_spec_identifier(spec.method))
			.join(', ')}} from '$lib/action_specs.js';

		export const Action_Message = {
			${registry.specs
				.map((spec) => {
					const {method} = spec;
					if (is_request_response_action(spec)) {
						return `${method}_request: Action_Message_Base.extend({
							method: z.literal('${method}'),
							params: ${to_action_spec_params_identifier(method)},
						}),
						${method}_response: Action_Message_Base.extend({
							method: z.literal('${method}'),
							params: ${to_action_spec_response_params_identifier(method)},
						})`;
					} else {
						return `${method}: Action_Message_Base.extend({
							method: z.literal('${method}'),
							params: ${to_action_spec_params_identifier(method)},
						})`;
					}
				})
				.join(',\n\t\t\t')}
		};
		export interface Action_Message {
			${registry.specs
				.map((spec) => {
					const {method} = spec;
					if (is_request_response_action(spec)) {
						return `${method}_request: z.infer<typeof Action_Message.${method}_request>,
						${method}_response: z.infer<typeof Action_Message.${method}_response>`;
					} else {
						return `${method}: z.infer<typeof Action_Message.${method}>`;
					}
				})
				.join(';\n\t\t\t')}
		}

		export type Action_Message_Name = keyof Action_Message;

		export interface Action_Message_Params {
			${registry.specs
				.map((spec) => {
					const {method} = spec;
					if (is_request_response_action(spec)) {
						return `${method}_request: z.infer<typeof ${to_action_spec_params_identifier(method)}>,
						${method}_response: z.infer<typeof ${to_action_spec_response_params_identifier(method)}>`;
					} else {
						return `${method}: z.infer<typeof ${to_action_spec_params_identifier(method)}>`;
					}
				})
				.join(',\n\t\t\t')}
		}

		// ${banner}
	`;
};
