import type {Gen} from '@ryanatkn/gro/gen.js';
import {z} from 'zod';

import {
	is_request_response_action,
	to_action_spec_params_identifier,
	to_action_spec_response_params_identifier,
} from '$lib/schema_helpers.js';
import {get_innermost_type} from '$lib/zod_helpers.js';
import {action_specs} from '$lib/action_collections.js';
import {Action_Registry} from '$lib/action_registry.js';
import {to_action_message_type} from '$lib/action_helpers.js';
import type {Action_Method} from '$lib/action_metatypes.js';
import type {Api_Request_Response_Flag} from '$lib/api.js';

/**
 * Outputs a file with action types that can be imported from anywhere with no runtime cost.
 */
export const gen: Gen = ({origin_path}) => {
	const registry = new Action_Registry(action_specs);

	// Get all schema names that need to be imported
	const schema_imports = registry.get_schema_imports();

	const banner = `generated by ${origin_path} - DO NOT EDIT OR RISK LOST DATA`;

	return `
		// ${banner}

		import {z} from 'zod';
		import type {Api_Result} from '$lib/api.js';
		import type {Mutation} from '$lib/mutation.js';
		import type {${schema_imports.join(', ')}} from '$lib/action_specs.js';
		import type { Zzz } from '$lib/zzz.svelte.js';

		/**
		 * All action method names. Request/response actions have two types per method.
		 */
		export const Action_Method = z.enum([
			${registry.specs.map(({method}) => `'${method}'`).join(',\n\t')}
		]);
		export type Action_Method = z.infer<typeof Action_Method>;

		/**
		 * Names of all request_response actions.
		 */
		export type Request_Response_Action_Method = ${
			registry.request_response_specs.map((spec) => `'${spec.method}'`).join(' | ') || 'never'
		};

		/**
		 * Names of all server_notification actions.
		 */
		export type Server_Notification_Action_Method = ${
			registry.server_notification_specs.map((spec) => `'${spec.method}'`).join(' | ') || 'never'
		};

		/**
		 * Names of all client_local actions.
		 */
		export type Client_Local_Action_Method = ${
			registry.client_local_specs.map((spec) => `'${spec.method}'`).join(' | ') || 'never'
		};

		/**
		 * All action types. May have '/' separators for namespacing.
		 * TODO maybe any relative url-encoded path is valid? add to schema defs
		 */
		export const Action_Message_Type = z.enum([
			${registry.specs
				.map((spec) =>
					spec.kind === 'request_response'
						? [
								`'${to_action_message_type(spec.method, 'request')}'`,
								`'${to_action_message_type(spec.method, 'response')}'`,
							]
						: `'${spec.method}'`,
				)
				.flat()
				.join(',\n\t')}
		]);
		export type Action_Message_Type = z.infer<typeof Action_Message_Type>;

		/**
		 * Interface for action dispatch functions.
		 */
		export interface Actions_Api {
			${registry.specs
				.map((spec) => {
					const innermost_type_name = get_innermost_type(spec.params)._def.typeName;
					const has_params =
						innermost_type_name !== z.ZodFirstPartyTypeKind.ZodNull &&
						innermost_type_name !== z.ZodFirstPartyTypeKind.ZodVoid;
					return `${spec.method}: (${
						has_params
							? `params: z.infer<typeof ${to_action_spec_params_identifier(spec.method)}>`
							: 'params?: void'
					}) => ${
						spec.kind === 'request_response'
							? `Promise<Api_Result<z.infer<typeof ${to_action_spec_response_params_identifier(spec.method)}>>>`
							: spec.kind === 'client_local'
								? spec.returns
								: 'void'
					};`;
				})
				.join('\n\t')}
		}

		// TODO maybe extract to $lib/mutation_types.ts or similar, decoupled
		/**
		 * Interface for client-side mutation handlers.
		 */
		export interface Mutations<T_App extends Zzz = Zzz> extends Partial<Record<Action_Message_Type, Mutation<T_App>>> {
			${registry.specs
				.map((spec) => {
					const v = (m: Action_Method, request_response: Api_Request_Response_Flag) =>
						`${to_action_message_type(
							m,
							request_response,
						)}?: Mutation<T_App, z.infer<typeof ${to_action_spec_params_identifier(m)}>, ${
							request_response === 'response'
								? `Api_Result<z.infer<typeof ${to_action_spec_response_params_identifier(m)}>>`
								: 'void'
						}>;`;
					return is_request_response_action(spec)
						? [v(spec.method, 'request'), v(spec.method, 'response')]
						: v(spec.method, null);
				})
				.flat()
				.join('\n\t')}
		}

		// ${banner}
	`;
};
