import type {Gen} from '@ryanatkn/gro/gen.js';

import {action_specs} from '$lib/action_collections.js';
import {Action_Registry} from '$lib/action_registry.js';
import type {Action_Method} from '$lib/action_metatypes.js';
import {
	to_action_request_message_type,
	to_action_response_message_type,
} from '$lib/action_helpers.js';

/**
 * Outputs a file with action collection types that can be imported by schemas.ts.
 * This is separate from action_metatypes.gen.ts to avoid circular dependencies.
 */
export const gen: Gen = ({origin_path}) => {
	const registry = new Action_Registry(action_specs);

	// TODO these are broken/hacky
	const client_methods = registry.client_methods;
	const networked_methods = registry.networked_methods;
	const nonnetworked_methods = registry.nonnetworked_methods;
	const service_methods = registry.service_methods;
	const all_methods = [...client_methods, ...service_methods];
	const from_client_methods = registry.client_to_server_methods;
	const from_server_methods = registry.server_to_client_methods;

	const banner = `generated by ${origin_path} - DO NOT EDIT OR RISK LOST DATA`;

	// Generate a list of action message references
	const get_action_messages = (
		methods: Array<Action_Method>,
		include_request_response: 'request' | 'response' | 'both',
	) => {
		let v = '';
		for (const method of methods) {
			// If it's a request-response action, we need to use the _request suffix
			const is_request_response = registry.request_response_specs.some(
				(spec) => spec.method === method,
			);

			if (!is_request_response) {
				v += `Action_Message.${method},`;
			} else {
				if (include_request_response === 'request' || include_request_response === 'both') {
					v += `Action_Message.${to_action_request_message_type(method)},`;
				}
				if (include_request_response === 'response' || include_request_response === 'both') {
					v += `Action_Message.${to_action_response_message_type(method)},`;
				}
			}
		}

		return v;
	};

	return `
		// ${banner}

		import {z} from 'zod';

		import {type Action_Spec, collect_action_specs_by_method} from '$lib/action_spec.js';
		import {Action_Message} from '$lib/action_messages.js';
		import * as action_spec_module from '$lib/action_specs.js';
		import type {Action_Method} from '$lib/action_metatypes.js';

		/**
		 * All method types combined.
		 */
		export const Action_Method_Any = z.enum([
			${all_methods.map((method) => `'${method}'`).join(',\n\t\t\t')}
		]);
		export type Action_Method_Any = z.infer<typeof Action_Method_Any>;

		/**
		 * Method types that can be sent from client to server.
		 */
		export const Action_Method_From_Client = z.enum([
			${from_client_methods.map((method) => `'${method}'`).join(',\n\t\t\t')}
		]);
		export type Action_Method_From_Client = z.infer<typeof Action_Method_From_Client>;

		/**
		 * Method types that can be sent from server to client.
		 */
		export const Action_Method_From_Server = z.enum([
			${from_server_methods.map((method) => `'${method}'`).join(',\n\t\t\t')}
		]);
		export type Action_Method_From_Server = z.infer<typeof Action_Method_From_Server>;

		/**
		 * Method types with network endpoints.
		 */
		export const Action_Method_Networked = z.enum([
			${networked_methods.map((method) => `'${method}'`).join(',\n\t\t\t')}
		]);
		export type Action_Method_Networked = z.infer<typeof Action_Method_Networked>;

		/**
		 * Method types without network endpoints.
		 */
		export const Action_Method_Nonnetworked = z.enum([
			${nonnetworked_methods.map((method) => `'${method}'`).join(',\n\t\t\t')}
		]);
		export type Action_Method_Nonnetworked = z.infer<typeof Action_Method_Nonnetworked>;

		/**
		 * All action types combined.
		 */
		export const Action_Message_Any = z.discriminatedUnion('type', [
			${get_action_messages(all_methods, 'both')}
		]);
		export type Action_Message_Any = z.infer<typeof Action_Message_Any>;

		/**
		 * Set of actions with "from_client" direction (originating from client).
		 */
		export const Action_Message_From_Client = z.discriminatedUnion('type', [
			${get_action_messages(from_client_methods, 'request')}
		]);
		export type Action_Message_From_Client = z.infer<typeof Action_Message_From_Client>;

		/**
		 * Set of actions with "from_server" direction (originating from server).
		 */
		export const Action_Message_From_Server = z.discriminatedUnion('type', [
			${get_action_messages(from_server_methods, 'response')}
		]);
		export type Action_Message_From_Server = z.infer<typeof Action_Message_From_Server>;

		/**
		 * Service actions with HTTP endpoints (networked).
		 */
		export const Action_Message_Networked = z.discriminatedUnion('type', [
			${get_action_messages(networked_methods, 'both')}
		]);
		export type Action_Message_Networked = z.infer<typeof Action_Message_Networked>;

		/**
		 * Service actions without HTTP endpoints (non-networked).
		 */
		export const Action_Message_Nonnetworked = z.discriminatedUnion('type', [
			${get_action_messages(nonnetworked_methods, 'both')}
		]);
		export type Action_Message_Nonnetworked = z.infer<typeof Action_Message_Nonnetworked>;

		export const action_specs: Array<Action_Spec> = collect_action_specs_by_method(action_spec_module);
		
		export const action_spec_by_method: Map<Action_Method, Action_Spec> = new Map(action_specs.map((spec) => [spec.method, spec]));


		// ${banner}
	`;
};
