// generated by src/lib/action_collections.gen.ts - DO NOT EDIT OR RISK LOST DATA

import {z} from 'zod';
import {Action_Message} from '$lib/action_messages.js';
import {
	ping_action_spec,
	pong_action_spec,
	load_session_action_spec,
	loaded_session_action_spec,
	filer_change_action_spec,
	update_diskfile_action_spec,
	delete_diskfile_action_spec,
	create_directory_action_spec,
	send_prompt_action_spec,
	completion_response_action_spec,
} from '$lib/action_specs.js';

/**
 * Set of client-only actions.
 */
export const Action_Client = z.discriminatedUnion('method', [
	Action_Message.update_diskfile,
	Action_Message.delete_diskfile,
	Action_Message.create_directory,
	Action_Message.send_prompt,
]);
export type Action_Client = z.infer<typeof Action_Client>;

/**
 * Set of server-only actions.
 */
export const Action_Server = z.discriminatedUnion('method', [
	Action_Message.ping,
	Action_Message.pong,
	Action_Message.load_session,
	Action_Message.loaded_session,
	Action_Message.filer_change,
	Action_Message.completion_response,
]);
export type Action_Server = z.infer<typeof Action_Server>;

/**
 * All action types combined.
 */
export const Action_Any = z.discriminatedUnion('method', [
	Action_Message.update_diskfile,
	Action_Message.delete_diskfile,
	Action_Message.create_directory,
	Action_Message.send_prompt,
	Action_Message.ping,
	Action_Message.pong,
	Action_Message.load_session,
	Action_Message.loaded_session,
	Action_Message.filer_change,
	Action_Message.completion_response,
]);
export type Action_Any = z.infer<typeof Action_Any>;

/**
 * Lookup map for action specifications by method name.
 */
export const action_spec_by_method = {
	ping: ping_action_spec,
	pong: pong_action_spec,
	load_session: load_session_action_spec,
	loaded_session: loaded_session_action_spec,
	filer_change: filer_change_action_spec,
	update_diskfile: update_diskfile_action_spec,
	delete_diskfile: delete_diskfile_action_spec,
	create_directory: create_directory_action_spec,
	send_prompt: send_prompt_action_spec,
	completion_response: completion_response_action_spec,
};

// generated by src/lib/action_collections.gen.ts - DO NOT EDIT OR RISK LOST DATA
