import type {Gen} from '@ryanatkn/gro/gen.js';

import {action_specs} from '$lib/action_collections.js';
import {Action_Registry} from '$lib/action_registry.js';
import type {Action_Method} from '$lib/action_metatypes.js';
import {
	to_action_request_message_type,
	to_action_response_message_type,
	to_action_spec_input_identifier,
	to_action_spec_output_identifier,
} from '$lib/action_helpers.js';

/**
 * Outputs a file with action collection types that can be imported by schemas.ts.
 * This is separate from `action_metatypes.gen.ts` to avoid circular dependencies.
 */
export const gen: Gen = ({origin_path}) => {
	const registry = new Action_Registry(action_specs);

	// TODO hacky
	const {
		client_methods,
		networked_methods,
		nonnetworked_methods,
		service_methods,
		client_to_server_methods,
		server_to_client_methods,
	} = registry;
	const all_methods = [...client_methods, ...service_methods];

	const banner = `generated by ${origin_path} - DO NOT EDIT OR RISK LOST DATA`;

	// Generate a list of action message references
	const get_action_messages = (
		methods: Array<Action_Method>,
		include_request_response: 'request' | 'response' | 'both',
	) => {
		let v = '';
		for (const method of methods) {
			// If it's a request-response action, we need to use the _request suffix
			const is_request_response = registry.request_response_specs.some(
				(spec) => spec.method === method,
			);

			if (!is_request_response) {
				v += `Action_Messages.${method},`;
			} else {
				if (include_request_response === 'request' || include_request_response === 'both') {
					v += `Action_Messages.${to_action_request_message_type(method)},`;
				}
				if (include_request_response === 'response' || include_request_response === 'both') {
					v += `Action_Messages.${to_action_response_message_type(method)},`;
				}
			}
		}

		return v;
	};

	return `
		// ${banner}

		import {z} from 'zod';

		import {type Action_Spec, collect_action_specs_by_method} from '$lib/action_spec.js';
		import {Action_Messages} from '$lib/action_messages.js';
		import * as specs from '$lib/action_specs.js';
		import type {Action_Method} from '$lib/action_metatypes.js';

		/**
		 * All method types combined.
		 */
		export const Action_Method_Any = z.enum([
			${all_methods.map((method) => `'${method}'`).join(',\n\t\t\t')}
		]);
		export type Action_Method_Any = z.infer<typeof Action_Method_Any>;

		/**
		 * Method types that can be sent from client to server.
		 */
		export const Action_Method_From_Client = z.enum([
			${client_to_server_methods.map((method) => `'${method}'`).join(',\n\t\t\t')}
		]);
		export type Action_Method_From_Client = z.infer<typeof Action_Method_From_Client>;

		/**
		 * Method types that can be sent from server to client.
		 */
		export const Action_Method_From_Server = z.enum([
			${server_to_client_methods.map((method) => `'${method}'`).join(',\n\t\t\t')}
		]);
		export type Action_Method_From_Server = z.infer<typeof Action_Method_From_Server>;

		/**
		 * Method types with network endpoints.
		 */
		export const Action_Method_Networked = z.enum([
			${networked_methods.map((method) => `'${method}'`).join(',\n\t\t\t')}
		]);
		export type Action_Method_Networked = z.infer<typeof Action_Method_Networked>;

		/**
		 * Method types without network endpoints.
		 */
		export const Action_Method_Nonnetworked = z.enum([
			${nonnetworked_methods.map((method) => `'${method}'`).join(',\n\t\t\t')}
		]);
		export type Action_Method_Nonnetworked = z.infer<typeof Action_Method_Nonnetworked>;

		// TODO is \`_Variant\` a better name than \`_Union\`? something else?
		/**
		 * All action types combined.
		 */
		export const Action_Message_Union = z.discriminatedUnion('type', [
			${get_action_messages(all_methods, 'both')}
		]);
		export type Action_Message_Union = z.infer<typeof Action_Message_Union>;

		/**
		 * Set of actions with "from_client" direction (originating from client).
		 */
		export const Action_Message_From_Client = z.discriminatedUnion('type', [
			${get_action_messages(client_to_server_methods, 'request')}
		]);
		export type Action_Message_From_Client = z.infer<typeof Action_Message_From_Client>;

		/**
		 * Set of actions with "from_server" direction (originating from server).
		 */
		export const Action_Message_From_Server = z.discriminatedUnion('type', [
			${get_action_messages(server_to_client_methods, 'response')}
		]);
		export type Action_Message_From_Server = z.infer<typeof Action_Message_From_Server>;

		/**
		 * Server actions with HTTP endpoints (networked).
		 */
		export const Action_Message_Networked = z.discriminatedUnion('type', [
			${get_action_messages(networked_methods, 'both')}
		]);
		export type Action_Message_Networked = z.infer<typeof Action_Message_Networked>;

		/**
		 * Server actions without HTTP endpoints (non-networked).
		 */
		export const Action_Message_Nonnetworked = z.discriminatedUnion('type', [
			${get_action_messages(nonnetworked_methods, 'both')}
		]);
		export type Action_Message_Nonnetworked = z.infer<typeof Action_Message_Nonnetworked>;

		export const action_specs: Array<Action_Spec> = collect_action_specs_by_method(specs);
		
		export const action_spec_by_method: Map<Action_Method, Action_Spec> = new Map(action_specs.map((spec) => [spec.method, spec]));

		/**
		 * Action parameter schemas indexed by method name.
		 * These represent the input data for each action,
		 * e.g. JSON-RPC request/notification params and local call arguments.
		 */
		export const Action_Inputs = {
			${registry.specs
				.map((spec) => `${spec.method}: specs.${to_action_spec_input_identifier(spec.method)}`)
				.join(',\n\t\t\t')}
		} as const;
		export interface Action_Inputs {
			${registry.specs
				.map(
					(spec) =>
						`${spec.method}: z.infer<typeof specs.${to_action_spec_input_identifier(spec.method)}>`,
				)
				.join(',\n\t\t\t')}
		}

		/**
		 * Action result schemas indexed by method name.
		 * These represent the output data for each action,
		 * e.g. JSON-RPC response results and local call return values.
		 */
		export const Action_Outputs = {
			${registry.specs
				.map((spec) => `${spec.method}: specs.${to_action_spec_output_identifier(spec.method)}`)
				.join(',\n\t\t\t')}
		} as const;
		export interface Action_Outputs {
			${registry.specs
				.map(
					(spec) =>
						`${spec.method}: z.infer<typeof specs.${to_action_spec_output_identifier(spec.method)}>`,
				)
				.join(',\n\t\t\t')}
		}

		// TODO BLOCK @api use the following or a variant and delete the stuff above

		/**
		 * Helper type to get params type for a method.
		 */
		export type Action_Input_For<T_Method extends keyof typeof Action_Inputs> = 
			z.infer<typeof Action_Inputs[T_Method]>;

		/**
		 * Helper type to get result type for a method.
		 */
		export type Action_Output_For<T_Method extends keyof typeof Action_Outputs> = 
			z.infer<typeof Action_Outputs[T_Method]>;

		/**
		 * Type guard to check if a method has params.
		 */
		export const has_action_params = (method: string): method is keyof typeof Action_Inputs =>
			method in Action_Inputs;

		/**
		 * Type guard to check if a method has results.
		 */
		export const has_action_result = (method: string): method is keyof typeof Action_Outputs =>
			method in Action_Outputs;

		/**
		 * Parse action params with validation.
		 */
		export const parse_action_input = <T_Method extends keyof typeof Action_Inputs>(
			method: T_Method,
			data: unknown
		): Action_Input_For<T_Method> =>
			Action_Inputs[method].parse(data);

		/**
		 * Parse action result with validation.
		 */
		export const parse_action_output = <T_Method extends keyof typeof Action_Outputs>(
			method: T_Method,
			data: unknown
		): Action_Output_For<T_Method> =>
			Action_Outputs[method].parse(data);

		/**
		 * Safe parse action params.
		 */
		export const safe_parse_action_input = <T_Method extends keyof typeof Action_Inputs>(
			method: T_Method,
			data: unknown
		): z.SafeParseReturnType<unknown, Action_Input_For<T_Method>> =>
			Action_Inputs[method].safeParse(data);

		/**
		 * Safe parse action result.
		 */
		export const safe_parse_action_output = <T_Method extends keyof typeof Action_Outputs>(
			method: T_Method,
			data: unknown
		): z.SafeParseReturnType<unknown, Action_Output_For<T_Method>> =>
			Action_Outputs[method].safeParse(data);

		// ${banner}
	`;
};
