import type {Gen} from '@ryanatkn/gro/gen.js';

import {action_specs} from '$lib/action_specs.js';
import {Action_Registry} from '$lib/action_registry.js';
import {to_action_spec_identifier} from '$lib/schema_helpers.js';

/**
 * Outputs a file with action collection types that can be imported by schemas.ts.
 * This is separate from action_metatypes.gen.ts to avoid circular dependencies.
 */
export const gen: Gen = ({origin_path}) => {
	const registry = new Action_Registry(action_specs);

	// TODO these are broken/hacky
	const client_methods = registry.client_methods;
	const networked_methods = registry.networked_methods;
	const nonnetworked_methods = registry.nonnetworked_methods;
	const service_methods = registry.service_methods;
	const all_methods = [...client_methods, ...service_methods];
	const from_client_methods = registry.from_client_methods;
	const from_server_methods = registry.from_server_methods;
	const from_either_methods = registry.from_either_methods;

	const banner = `generated by ${origin_path} - DO NOT EDIT OR RISK LOST DATA`;

	return `
		// ${banner}

		import {z} from 'zod';
		import {Action_Message} from '$lib/action_messages.js';
		import {${registry.specs
			.map((spec) => to_action_spec_identifier(spec.method))
			.join(', ')}} from '$lib/action_specs.js';

		/**
		 * Set of actions with "from_client" direction (originating from client).
		 */
		export const Action_From_Client = z.discriminatedUnion('method', [
			${from_client_methods.map((method) => `Action_Message.${method}`).join(',\n\t')}
		]);
		export type Action_From_Client = z.infer<typeof Action_From_Client>;

		/**
		 * Set of actions with "from_server" direction (originating from server).
		 */
		export const Action_From_Server = z.discriminatedUnion('method', [
			${from_server_methods.map((method) => `Action_Message.${method}`).join(',\n\t')}
		]);
		export type Action_From_Server = z.infer<typeof Action_From_Server>;

		/**
		 * Set of actions with "from_either" direction (can originate from either).
		 */
		export const Action_From_Either = z.discriminatedUnion('method', [
			${from_either_methods.map((method) => `Action_Message.${method}`).join(',\n\t')}
		]);
		export type Action_From_Either = z.infer<typeof Action_From_Either>;

		/**
		 * All action types combined.
		 */
		export const Action_Any = z.discriminatedUnion('method', [
			${all_methods.map((method) => `Action_Message.${method}`).join(',\n\t')}
		]);
		export type Action_Any = z.infer<typeof Action_Any>;

		/**
		 * Service actions with HTTP endpoints (networked).
		 */
		export const Action_Networked = z.discriminatedUnion('method', [
			${networked_methods.map((method) => `Action_Message.${method}`).join(',\n\t')}
		]);
		export type Action_Networked = z.infer<typeof Action_Networked>;

		/**
		 * Service actions without HTTP endpoints (non-networked).
		 */
		export const Action_Nonnetworked = z.discriminatedUnion('method', [
			${nonnetworked_methods.map((method) => `Action_Message.${method}`).join(',\n\t')}
		]);
		export type Action_Nonnetworked = z.infer<typeof Action_Nonnetworked>;

		/**
		 * Lookup map for action specifications by method name.
		 */
		export const action_spec_by_method = {
			${registry.specs
				.map((spec) => `${spec.method}: ${to_action_spec_identifier(spec.method)}`)
				.join(',\n\t\t\t')}
		};

		// ${banner}
	`;
};
