// generated by src/lib/action_messages.gen.ts - DO NOT EDIT OR RISK LOST DATA

import {z} from 'zod';

import {Action_Message_Base} from '$lib/action_spec.js';
import {
	create_directory_action_spec,
	delete_diskfile_action_spec,
	filer_change_action_spec,
	load_session_action_spec,
	ping_action_spec,
	submit_completion_action_spec,
	toggle_main_menu_action_spec,
	update_diskfile_action_spec,
} from '$lib/action_specs.js';

export const Action_Message = {
	create_directory_request: Action_Message_Base.extend({
		type: z.literal('create_directory_request'),
		method: z.literal('create_directory'),
		params: create_directory_action_spec.params,
	}),
	create_directory_response: Action_Message_Base.extend({
		type: z.literal('create_directory_response'),
		method: z.literal('create_directory'),
		params: create_directory_action_spec.response_params,
	}),
	delete_diskfile_request: Action_Message_Base.extend({
		type: z.literal('delete_diskfile_request'),
		method: z.literal('delete_diskfile'),
		params: delete_diskfile_action_spec.params,
	}),
	delete_diskfile_response: Action_Message_Base.extend({
		type: z.literal('delete_diskfile_response'),
		method: z.literal('delete_diskfile'),
		params: delete_diskfile_action_spec.response_params,
	}),
	filer_change: Action_Message_Base.extend({
		type: z.literal('filer_change'),
		method: z.literal('filer_change'),
		params: filer_change_action_spec.params,
	}),
	load_session_request: Action_Message_Base.extend({
		type: z.literal('load_session_request'),
		method: z.literal('load_session'),
		params: load_session_action_spec.params,
	}),
	load_session_response: Action_Message_Base.extend({
		type: z.literal('load_session_response'),
		method: z.literal('load_session'),
		params: load_session_action_spec.response_params,
	}),
	ping_request: Action_Message_Base.extend({
		type: z.literal('ping_request'),
		method: z.literal('ping'),
		params: ping_action_spec.params,
	}),
	ping_response: Action_Message_Base.extend({
		type: z.literal('ping_response'),
		method: z.literal('ping'),
		params: ping_action_spec.response_params,
	}),
	submit_completion_request: Action_Message_Base.extend({
		type: z.literal('submit_completion_request'),
		method: z.literal('submit_completion'),
		params: submit_completion_action_spec.params,
	}),
	submit_completion_response: Action_Message_Base.extend({
		type: z.literal('submit_completion_response'),
		method: z.literal('submit_completion'),
		params: submit_completion_action_spec.response_params,
	}),
	toggle_main_menu: Action_Message_Base.extend({
		type: z.literal('toggle_main_menu'),
		method: z.literal('toggle_main_menu'),
		params: toggle_main_menu_action_spec.params,
	}),
	update_diskfile_request: Action_Message_Base.extend({
		type: z.literal('update_diskfile_request'),
		method: z.literal('update_diskfile'),
		params: update_diskfile_action_spec.params,
	}),
	update_diskfile_response: Action_Message_Base.extend({
		type: z.literal('update_diskfile_response'),
		method: z.literal('update_diskfile'),
		params: update_diskfile_action_spec.response_params,
	}),
};
export interface Action_Message {
	create_directory_request: z.infer<typeof Action_Message.create_directory_request>;
	create_directory_response: z.infer<typeof Action_Message.create_directory_response>;
	delete_diskfile_request: z.infer<typeof Action_Message.delete_diskfile_request>;
	delete_diskfile_response: z.infer<typeof Action_Message.delete_diskfile_response>;
	filer_change: z.infer<typeof Action_Message.filer_change>;
	load_session_request: z.infer<typeof Action_Message.load_session_request>;
	load_session_response: z.infer<typeof Action_Message.load_session_response>;
	ping_request: z.infer<typeof Action_Message.ping_request>;
	ping_response: z.infer<typeof Action_Message.ping_response>;
	submit_completion_request: z.infer<typeof Action_Message.submit_completion_request>;
	submit_completion_response: z.infer<typeof Action_Message.submit_completion_response>;
	toggle_main_menu: z.infer<typeof Action_Message.toggle_main_menu>;
	update_diskfile_request: z.infer<typeof Action_Message.update_diskfile_request>;
	update_diskfile_response: z.infer<typeof Action_Message.update_diskfile_response>;
}

// generated by src/lib/action_messages.gen.ts - DO NOT EDIT OR RISK LOST DATA
