// generated by src/lib/action_metatypes.gen.ts - DO NOT EDIT OR RISK LOST DATA

import {z} from 'zod';

import type {Action_Inputs, Action_Outputs} from '$lib/action_collections.js';

/**
 * All action method names. Request/response actions have two types per method.
 */
export const Action_Method = z.enum([
	'create_directory',
	'delete_diskfile',
	'filer_change',
	'load_session',
	'ping',
	'submit_completion',
	'toggle_main_menu',
	'update_diskfile',
]);
export type Action_Method = z.infer<typeof Action_Method>;

/**
 * Names of all request_response actions.
 */
export const Request_Response_Action_Method = z.enum([
	'create_directory',
	'delete_diskfile',
	'load_session',
	'ping',
	'submit_completion',
	'update_diskfile',
]);
export type Request_Response_Action_Method = z.infer<typeof Request_Response_Action_Method>;

/**
 * Names of all remote_notification actions.
 */
export const Remote_Notification_Action_Method = z.enum(['filer_change']);
export type Remote_Notification_Action_Method = z.infer<typeof Remote_Notification_Action_Method>;

/**
 * Names of all local_call actions.
 */
export const Local_Call_Action_Method = z.enum(['toggle_main_menu']);
export type Local_Call_Action_Method = z.infer<typeof Local_Call_Action_Method>;

/**
 * Names of all actions that may be handled on the client.
 */
export const Frontend_Action_Method = z.enum([
	'create_directory',
	'delete_diskfile',
	'filer_change',
	'load_session',
	'ping',
	'submit_completion',
	'toggle_main_menu',
	'update_diskfile',
]);
export type Frontend_Action_Method = z.infer<typeof Frontend_Action_Method>;

/**
 * Names of all actions that may be handled on the server.
 */
export const Backend_Action_Method = z.enum([
	'create_directory',
	'delete_diskfile',
	'filer_change',
	'load_session',
	'ping',
	'submit_completion',
	'update_diskfile',
]);
export type Backend_Action_Method = z.infer<typeof Backend_Action_Method>;

/**
 * Interface for action dispatch functions.
 */
export interface Actions_Api {
	create_directory: (
		input: Action_Inputs['create_directory'],
	) => Promise<Action_Outputs['create_directory']>;
	delete_diskfile: (
		input: Action_Inputs['delete_diskfile'],
	) => Promise<Action_Outputs['delete_diskfile']>;
	filer_change: (input: Action_Inputs['filer_change']) => Promise<Action_Outputs['filer_change']>;
	load_session: (input?: void) => Promise<Action_Outputs['load_session']>;
	ping: (input?: void) => Promise<Action_Outputs['ping']>;
	submit_completion: (
		input: Action_Inputs['submit_completion'],
	) => Promise<Action_Outputs['submit_completion']>;
	toggle_main_menu: (
		input?: Action_Inputs['toggle_main_menu'],
	) => Action_Outputs['toggle_main_menu'];
	update_diskfile: (
		input: Action_Inputs['update_diskfile'],
	) => Promise<Action_Outputs['update_diskfile']>;
}

// generated by src/lib/action_metatypes.gen.ts - DO NOT EDIT OR RISK LOST DATA
