// generated by src/lib/action_types.gen.ts - DO NOT EDIT OR RISK LOST DATA

import {z} from 'zod';
import type {Api_Result} from '$lib/api.js';
import type {
	Service_Return,
	Non_Authenticated_Service,
	Non_Authorized_Service,
	Authorized_Service,
} from '$lib/server/service.js';
import type {Mutation} from '$lib/mutation.js';
import type {
	completion_response_action_spec,
	create_directory_action_spec,
	delete_diskfile_action_spec,
	filer_change_action_spec,
	load_session_action_spec,
	loaded_session_action_spec,
	ping_action_spec,
	pong_action_spec,
	send_prompt_action_spec,
	update_diskfile_action_spec,
} from '$lib/action_specs.js';

/**
 * All action names. May have '/' separators for namespacing.
 * TODO maybe any relative url-encoded path is valid? add to schema defs
 */
export const Action_Method = z.enum([
	'ping',
	'pong',
	'load_session',
	'loaded_session',
	'filer_change',
	'update_diskfile',
	'delete_diskfile',
	'create_directory',
	'send_prompt',
	'completion_response',
]);
export type Action_Method = z.infer<typeof Action_Method>;

/**
 * Names of all service actions.
 */
export type Service_Action_Method =
	| 'ping'
	| 'pong'
	| 'load_session'
	| 'loaded_session'
	| 'filer_change'
	| 'completion_response';

/**
 * Names of all client-only actions.
 */
export type Client_Action_Method =
	| 'update_diskfile'
	| 'delete_diskfile'
	| 'create_directory'
	| 'send_prompt';

/**
 * Maps action names to their parameter types.
 */
export interface Action_Params_By_Name {
	ping: ping_action_spec.params;
	pong: pong_action_spec.params;
	load_session: load_session_action_spec.params;
	loaded_session: loaded_session_action_spec.params;
	filer_change: filer_change_action_spec.params;
	update_diskfile: update_diskfile_action_spec.params;
	delete_diskfile: delete_diskfile_action_spec.params;
	create_directory: create_directory_action_spec.params;
	send_prompt: send_prompt_action_spec.params;
	completion_response: completion_response_action_spec.params;
}

/**
 * Maps action names to their response types (server actions only).
 */
export interface Action_Response_By_Name {
	ping: Ping_Action_Response;
	pong: Pong_Action_Response;
	load_session: Load_Session_Action_Response;
	loaded_session: Loaded_Session_Action_Response;
	filer_change: Filer_Change_Action_Response;
	completion_response: Completion_Response_Action_Response;
}

/**
 * Maps action names to their service implementations.
 */
export interface Service_By_Name {
	ping: Non_Authenticated_Service<ping_action_spec, Service_Return<Ping_Action_Response>>;
	pong: Non_Authenticated_Service<pong_action_spec, Service_Return<Pong_Action_Response>>;
	load_session: Non_Authenticated_Service<
		load_session_action_spec,
		Service_Return<Load_Session_Action_Response>
	>;
	loaded_session: Non_Authenticated_Service<
		loaded_session_action_spec,
		Service_Return<Loaded_Session_Action_Response>
	>;
	filer_change: Non_Authenticated_Service<
		filer_change_action_spec,
		Service_Return<Filer_Change_Action_Response>
	>;
	completion_response: Non_Authenticated_Service<
		completion_response_action_spec,
		Service_Return<Completion_Response_Action_Response>
	>;
}

/**
 * Interface for action dispatch functions.
 */
export interface Actions {
	ping: () => Promise<Api_Result<Ping_Action_Response>>;
	pong: (params: pong_action_spec.params) => Promise<Api_Result<Pong_Action_Response>>;
	load_session: () => Promise<Api_Result<Load_Session_Action_Response>>;
	loaded_session: (
		params: loaded_session_action_spec.params,
	) => Promise<Api_Result<Loaded_Session_Action_Response>>;
	filer_change: (
		params: filer_change_action_spec.params,
	) => Promise<Api_Result<Filer_Change_Action_Response>>;
	update_diskfile: (params: update_diskfile_action_spec.params) => Promise<string>;
	delete_diskfile: (params: delete_diskfile_action_spec.params) => Promise<string>;
	create_directory: (params: create_directory_action_spec.params) => Promise<string>;
	send_prompt: (params: send_prompt_action_spec.params) => Promise<string>;
	completion_response: (
		params: completion_response_action_spec.params,
	) => Promise<Api_Result<Completion_Response_Action_Response>>;
}

// TODO maybe extract to $lib/mutation_types.ts or similar, decoupled
/**
 * Interface for client-side mutation handlers.
 */
export interface Mutations {
	[key: string]: Mutation | undefined;
	ping?: Mutation<ping_action_spec, Api_Result<Ping_Action_Response>>;
	pong?: Mutation<pong_action_spec, Api_Result<Pong_Action_Response>>;
	load_session?: Mutation<load_session_action_spec, Api_Result<Load_Session_Action_Response>>;
	loaded_session?: Mutation<loaded_session_action_spec, Api_Result<Loaded_Session_Action_Response>>;
	filer_change?: Mutation<filer_change_action_spec, Api_Result<Filer_Change_Action_Response>>;
	update_diskfile?: Mutation<update_diskfile_action_spec, void>;
	delete_diskfile?: Mutation<delete_diskfile_action_spec, void>;
	create_directory?: Mutation<create_directory_action_spec, void>;
	send_prompt?: Mutation<send_prompt_action_spec, void>;
	completion_response?: Mutation<
		completion_response_action_spec,
		Api_Result<Completion_Response_Action_Response>
	>;
}

// generated by src/lib/action_types.gen.ts - DO NOT EDIT OR RISK LOST DATA
