import type {Gen} from '@ryanatkn/gro/gen.js';
import {z} from 'zod';

import {get_innermost_type} from '$lib/zod_helpers.js';
import {action_specs} from '$lib/action_collections.js';
import {Action_Registry} from '$lib/action_registry.js';
import {
	to_action_spec_input_identifier,
	to_action_spec_output_identifier,
	to_action_message_type,
	to_action_request_message_type,
	to_action_response_message_type,
} from '$lib/action_helpers.js';
import {ACTION_KIND_PHASES, type Action_Phase} from '$lib/action_types.js';

/**
 * Outputs a file with generated types and schemas using the action specs as the source of truth.
 */
export const gen: Gen = ({origin_path}) => {
	const registry = new Action_Registry(action_specs);

	// Get all schema names that need to be imported
	const schema_imports = registry.get_schema_imports();

	const banner = `generated by ${origin_path} - DO NOT EDIT OR RISK LOST DATA`;

	// TODO BLOCK @api probably extract a helper to avoid repetition
	// Helper to generate phase handlers based on ACTION_KIND_PHASES
	const generate_phase_handlers = (spec: (typeof registry.specs)[0]): string => {
		const {method, kind} = spec;
		const phases = ACTION_KIND_PHASES[kind];

		const phase_handlers = phases
			.map((phase: Action_Phase) => {
				// Determine params and result types based on phase
				let params_type: string;
				let result_type: string;

				switch (phase) {
					case 'send_request':
					case 'receive_request':
						params_type = `Action_Message_Params['${to_action_request_message_type(method)}']`;
						result_type =
							phase === 'receive_request' && kind === 'request_response'
								? `Action_Message_Params['${to_action_response_message_type(method)}']`
								: 'void';
						break;
					case 'send_response':
					case 'receive_response':
						params_type =
							kind === 'request_response'
								? phase === 'send_response'
									? `Action_Message_Params['${to_action_response_message_type(method)}']`
									: `Action_Message_Params['${to_action_request_message_type(method)}']`
								: 'never';
						result_type =
							kind === 'request_response'
								? phase === 'receive_response'
									? `Action_Message_Params['${to_action_response_message_type(method)}']`
									: 'void'
								: 'never';
						break;
					case 'send':
					case 'receive':
						params_type = `Action_Message_Params['${method}']`;
						result_type = 'void';
						break;
					case 'execute':
						params_type = `Action_Message_Params['${method}']`;
						result_type = spec.returns || 'void';
						break;
					default:
						params_type = 'never';
						result_type = 'never';
				}

				return `${phase}?: Client_Action_Handler<
			T_App,
			${params_type},
			${result_type}
		>`;
			})
			.join(';\n\t\t');

		return `${method}?: {\n\t\t${phase_handlers};\n\t}`;
	};

	return `
		// ${banner}

		import {z} from 'zod';

		import type {Client_Action_Handler} from '$lib/client_action_handler.js';
		import type {${schema_imports.join(', ')}} from '$lib/action_specs.js';
		import type {Zzz_App} from '$lib/zzz_app.svelte.js';

		/**
		 * All action method names. Request/response actions have two types per method.
		 */
		export const Action_Method = z.enum([
			${registry.specs.map(({method}) => `'${method}'`).join(',\n\t')}
		]);
		export type Action_Method = z.infer<typeof Action_Method>;

		/**
		 * Names of all request_response actions.
		 */
		export type Request_Response_Action_Method = ${
			registry.request_response_specs.map((spec) => `'${spec.method}'`).join(' | ') || 'never'
		};

		/**
		 * Names of all remote_notification actions.
		 */
		export type Remote_Notification_Action_Method = ${
			registry.remote_notification_specs.map((spec) => `'${spec.method}'`).join(' | ') || 'never'
		};

		/**
		 * Names of all local_call actions.
		 */
		export type Local_Call_Action_Method = ${
			registry.local_call_specs.map((spec) => `'${spec.method}'`).join(' | ') || 'never'
		};

		/**
		 * All action types. May have '/' separators for namespacing.
		 * TODO maybe any relative url-encoded path is valid? add to schema defs
		 */
		export const Action_Message_Type = z.enum([
			${registry.specs
				.map((spec) =>
					spec.kind === 'request_response'
						? [
								`'${to_action_message_type(spec.method, 'request')}'`,
								`'${to_action_message_type(spec.method, 'response')}'`,
							]
						: `'${spec.method}'`,
				)
				.flat()
				.join(',\n\t')}
		]);
		export type Action_Message_Type = z.infer<typeof Action_Message_Type>;

		export interface Action_Message_Params {
			${registry.specs
				.map((spec) => {
					const {method} = spec;
					if (spec.kind === 'request_response') {
						return `${to_action_request_message_type(method)}: z.infer<typeof ${to_action_spec_input_identifier(method)}>,
						${to_action_response_message_type(method)}: z.infer<typeof ${to_action_spec_output_identifier(method)}>`;
					} else {
						return `${method}: z.infer<typeof ${to_action_spec_input_identifier(method)}>`;
					}
				})
				.join(',\n\t\t\t')}
		}

		/**
		 * Interface for action dispatch functions.
		 */
		export interface Actions_Api {
			${registry.specs
				.map((spec) => {
					const innermost_type_name = get_innermost_type(spec.input)._def.typeName;
					const has_params =
						innermost_type_name !== z.ZodFirstPartyTypeKind.ZodNull &&
						innermost_type_name !== z.ZodFirstPartyTypeKind.ZodVoid;
					return `${spec.method}: (${
						has_params
							? `params${spec.input.isOptional() ? '?' : ''}: Action_Message_Params['${to_action_message_type(
									spec.method,
									spec.kind === 'request_response' ? 'request' : null,
								)}']`
							: 'params?: void'
					}) => ${
						spec.kind === 'request_response'
							? `Promise<Action_Message_Params['${to_action_response_message_type(spec.method)}']>`
							: spec.kind === 'local_call'
								? spec.returns
								: 'void'
					};`;
				})
				.join('\n\t')}
		}

		/**
		 * Interface for client-side action handlers organized by method and phase.
		 */
		export interface Client_Action_Handlers<T_App extends Zzz_App = Zzz_App> {
			${registry.specs.map(generate_phase_handlers).join(';\n\t')}
		}

		// ${banner}
	`;
};
