import type {Gen} from '@ryanatkn/gro/gen.js';

import {to_action_spec_identifier, to_action_spec_params_identifier} from '$lib/schema_helpers.js';
import {action_specs} from '$lib/action_specs.js';
import {Action_Registry} from '$lib/action_registry.js';

/**
 * Outputs a file with action schema definitions that can be imported by other modules.
 * This separates schema definitions from their usage in collections.
 */
export const gen: Gen = ({origin_path}) => {
	const registry = new Action_Registry(action_specs);

	const banner = `generated by ${origin_path} - DO NOT EDIT OR RISK LOST DATA`;

	return `
		// ${banner}

		import {z} from 'zod';
		import {Action_Base} from '$lib/action_spec.js';
		import {${registry.specs
			.map((spec) => to_action_spec_identifier(spec.method))
			.join(', ')}} from '$lib/action_specs.js';

		${registry.specs
			.map((spec) => {
				const {method} = spec;
				const identifier = to_action_spec_identifier(method);
				return `
					export const ${identifier} = Action_Base.extend({
						method: z.literal('${method}'),
						params: ${to_action_spec_params_identifier(method)};
					export type ${identifier} = z.infer<typeof ${identifier}>;
				`;
			})
			.join('\n\n')}

		// ${banner}
	`;
};
