import type {Gen} from '@ryanatkn/gro/gen.js';

import {global_action_registry} from '$lib/action_registry_global.js';
import type {Action_Spec} from '$lib/schemas.js';
import {to_action_params_name} from '$lib/schema_helpers.js';

/**
 * Outputs a file with action schema definitions that can be imported by other modules.
 * This separates schema definitions from their usage in collections.
 */
export const gen: Gen = ({origin_path}) => {
	const registry = global_action_registry;

	// Generate schema code for each action type
	const generate_action_message_code = (spec: Action_Spec): string => {
		const params_name = to_action_params_name(spec.method);
		const identifier = `${spec.method}_action_message`;
		return `
export const ${identifier} = Action_Base.extend({
	method: z.literal('${spec.method}'),
	params: ${params_name},
});
export type ${identifier} = z.infer<typeof ${identifier}>;`;
	};

	// Generate schema entries for all actions
	const action_message_entries = registry.specs.map(generate_action_message_code);

	const banner = `generated by ${origin_path} - DO NOT EDIT OR RISK LOST DATA`;

	return `
// ${banner}

import {z} from 'zod';
import {
	Action_Base, ${
		// Import all needed param types
		registry.specs.map((spec) => to_action_params_name(spec.method)).join(', ')
	}} from '$lib/schemas.js';

${action_message_entries.join('\n\n')}

// ${banner}
`.trim();
};
