import type {Gen} from '@ryanatkn/gro/gen.js';
import {z} from 'zod';

import {action_specs} from '$lib/schema_metadata.js';
import {
	to_action_params_name,
	to_action_response_name,
	get_schema_imports,
	is_service_action,
	is_client_action,
} from '$lib/schema_helpers.js';
import {get_innermost_type} from '$lib/zod_helpers.js';

/**
 * Outputs a file with action types that can be imported from anywhere with no runtime cost.
 */
export const gen: Gen = ({origin_path}) => {
	// Get all schema names that need to be imported
	const schema_imports = get_schema_imports(action_specs);

	// Extract all action names for generating the Action_Name enum
	const action_names = action_specs.map((spec) => spec.name);

	const banner = `generated by ${origin_path} - DO NOT EDIT OR RISK LOST DATA`;

	return `
// ${banner}

import {z} from 'zod';
import type {Api_Result} from '$lib/api.js';
import type {Service_Return, Non_Authenticated_Service, Non_Authorized_Service, Authorized_Service} from '$lib/server/service.js';
import type {Mutation} from '$lib/mutation.js';
import type {${schema_imports.join(', ')}} from '$lib/schemas.js';

/**
 * All action names.
 */
export const Action_Name = z.enum([
	${action_names.map((name) => `'${name}'`).join(',\n\t')}
]);
export type Action_Name = z.infer<typeof Action_Name>;

/**
 * Names of all service actions.
 */
export type Service_Action_Name = ${
		action_specs
			.filter(is_service_action)
			.map((spec) => `'${spec.name}'`)
			.join(' | ') || 'never'
	};

/**
 * Names of all client-only actions.
 */
export type Client_Action_Name = ${
		action_specs
			.filter(is_client_action)
			.map((spec) => `'${spec.name}'`)
			.join(' | ') || 'never'
	};

/**
 * Maps action names to their parameter types.
 */
export interface Action_Params_By_Name {
	${action_specs.map((spec) => `${spec.name}: ${to_action_params_name(spec.name)};`).join('\n\t')}
}

/**
 * Maps action names to their response types (server actions only).
 */
export interface Action_Response_By_Name {
	${action_specs
		.filter(is_service_action)
		.map((spec) => `${spec.name}: ${to_action_response_name(spec.name)};`)
		.join('\n\t')}
}

/**
 * Maps action names to their service implementations.
 */
export interface Service_By_Name {
	${action_specs
		.filter(is_service_action)
		.map(
			(spec) =>
				`${spec.name}: Non_Authenticated_Service<${to_action_params_name(spec.name)}, Service_Return<${to_action_response_name(spec.name)}>>;`,
		)
		.join('\n\t')}
}

/**
 * Interface for action dispatch functions.
 */
export interface Actions {
	${action_specs
		.map((spec) => {
			const hasParams =
				get_innermost_type(spec.params)._def.typeName !== z.ZodFirstPartyTypeKind.ZodNull;
			return `${spec.name}: (${hasParams ? `params: ${to_action_params_name(spec.name)}` : ''}) => Promise<${spec.returns}>;`;
		})
		.join('\n\t')}
}

/**
 * Interface for client-side mutation handlers.
 */
export interface Mutations {
	[key: string]: Mutation | undefined;
	${action_specs
		.map((spec) => {
			const responseType = is_service_action(spec)
				? `Api_Result<${to_action_response_name(spec.name)}>`
				: 'void';
			return `${spec.name}?: Mutation<${to_action_params_name(spec.name)}, ${responseType}>;`;
		})
		.join('\n\t')}
}

// ${banner}
`.trim();
};
