import type {Gen} from '@ryanatkn/gro/gen.js';
import {z} from 'zod';

import {global_action_registry} from '$lib/action_registry_global.js';
import {to_action_params_name, to_action_response_name} from '$lib/schema_helpers.js';
import {get_innermost_type} from '$lib/zod_helpers.js';

/**
 * Outputs a file with action types that can be imported from anywhere with no runtime cost.
 */
export const gen: Gen = ({origin_path}) => {
	const registry = global_action_registry;

	// Get all schema names that need to be imported
	const schema_imports = registry.get_schema_imports();

	// Extract all action names for generating the Action_Method enum
	const methods = registry.specs.map((spec) => spec.method);

	const banner = `generated by ${origin_path} - DO NOT EDIT OR RISK LOST DATA`;

	return `
// ${banner}

import {z} from 'zod';
import type {Api_Result} from '$lib/api.js';
import type {Service_Return, Non_Authenticated_Service, Non_Authorized_Service, Authorized_Service} from '$lib/server/service.js';
import type {Mutation} from '$lib/mutation.js';
import type {${schema_imports.join(', ')}} from '$lib/schemas.js';

/**
 * All action names.
 */
export const Action_Method = z.enum([
	${methods.map((name) => `'${name}'`).join(',\n\t')}
]);
export type Action_Method = z.infer<typeof Action_Method>;

/**
 * Names of all service actions.
 */
export type Service_Action_Method = ${
		registry.service_specs.map((spec) => `'${spec.method}'`).join(' | ') || 'never'
	};

/**
 * Names of all client-only actions.
 */
export type Client_Action_Method = ${
		registry.client_specs.map((spec) => `'${spec.method}'`).join(' | ') || 'never'
	};

/**
 * Maps action names to their parameter types.
 */
export interface Action_Params_By_Name {
	${registry.specs.map((spec) => `${spec.method}: ${to_action_params_name(spec.method)};`).join('\n\t')}
}

/**
 * Maps action names to their response types (server actions only).
 */
export interface Action_Response_By_Name {
	${registry.service_specs
		.map((spec) => `${spec.method}: ${to_action_response_name(spec.method)};`)
		.join('\n\t')}
}

/**
 * Maps action names to their service implementations.
 */
export interface Service_By_Name {
	${registry.service_specs
		.map(
			(spec) =>
				`${spec.method}: Non_Authenticated_Service<${to_action_params_name(spec.method)}, Service_Return<${to_action_response_name(spec.method)}>>;`,
		)
		.join('\n\t')}
}

/**
 * Interface for action dispatch functions.
 */
export interface Actions {
	${registry.specs
		.map((spec) => {
			const hasParams =
				get_innermost_type(spec.params)._def.typeName !== z.ZodFirstPartyTypeKind.ZodNull;
			return `${spec.method}: (${hasParams ? `params: ${to_action_params_name(spec.method)}` : ''}) => Promise<${spec.returns}>;`;
		})
		.join('\n\t')}
}

// TODO maybe extract to $lib/mutation_types.ts or similar, decoupled
/**
 * Interface for client-side mutation handlers.
 */
export interface Mutations {
	[key: string]: Mutation | undefined;
	${registry.specs
		.map((spec) => {
			const responseType =
				spec.type === 'Service_Action'
					? `Api_Result<${to_action_response_name(spec.method)}>`
					: 'void';
			return `${spec.method}?: Mutation<${to_action_params_name(spec.method)}, ${responseType}>;`;
		})
		.join('\n\t')}
}

// ${banner}
`.trim();
};
