import type {Gen} from '@ryanatkn/gro/gen.js';

import {action_specs} from '$lib/action_collections.js';
import {Action_Registry} from '$lib/action_registry.js';
import {ACTION_KIND_PHASES, type Action_Phase} from '$lib/action_types.js';

// TODO @api may not be needed, try to replace with regular types

/**
 * Outputs a file with generated types and schemas using the action specs as the source of truth.
 */
export const gen: Gen = ({origin_path}) => {
	const registry = new Action_Registry(action_specs);

	const banner = `generated by ${origin_path} - DO NOT EDIT OR RISK LOST DATA`;

	// TODO BLOCK @api get these correct, and maybe have a handler type that is more generic
	const generate_phase_handlers = (spec: (typeof registry.specs)[0]): string => {
		const {method, kind} = spec;
		const phases = ACTION_KIND_PHASES[kind];

		const phase_handlers = phases
			.map((phase: Action_Phase) => {
				let returned_type = spec.returns || `Action_Outputs['${method}']`;
				if (spec.async) {
					returned_type = `Promise<${returned_type}>`;
				}

				return `${phase}?: Client_Action_Handler<
					T_App,
					Action_Inputs['${method}'],
					Action_Outputs['${method}'],
					${returned_type}
				>`;
			})
			.join(';\n\t\t');

		return `${method}?: {\n\t\t${phase_handlers};\n\t}`;
	};

	return `
		// ${banner}

		import type {Client_Action_Handler} from '$lib/client_action_handler.js';
		import type {Action_Inputs, Action_Outputs} from '$lib/action_collections.js';
		import type {Zzz_App} from '$lib/zzz_app.svelte.js';

		/**
		 * Interface for client-side action handlers organized by method and phase.
		 */
		export interface Client_Action_Handlers<T_App extends Zzz_App = Zzz_App> {
			${registry.specs.map(generate_phase_handlers).join(';\n\t')}
		}

		// ${banner}
	`;
};
