<script lang="ts">
	import {base} from '$app/paths';
	import type {Snippet} from 'svelte';
	import {zzz_logo} from '@ryanatkn/fuz/logos.js';
	import Svg from '@ryanatkn/fuz/Svg.svelte';

	import Nav_Link from '$lib/Nav_Link.svelte';
	import {
		SYMBOL_CAPABILITIES,
		SYMBOL_CHAT,
		SYMBOL_FILE,
		SYMBOL_MODEL,
		SYMBOL_PROMPTS,
		SYMBOL_PROVIDER,
		SYMBOL_SETTINGS,
	} from '$lib/constants.js';

	interface Props {
		children: Snippet;
	}

	const {children}: Props = $props();

	const SIDEBAR_WIDTH_MAX = 200;
	const sidebar_width = $state(SIDEBAR_WIDTH_MAX);

	// TODO dashboard should be mounted with Markdown
</script>

<!-- TODO drive with data -->
<div class="dashboard" style:--sidebar_width="{sidebar_width}px">
	<div class="h_100 w_100 fixed t_0 l_0" style:padding-left="var(--sidebar_width)">
		{@render children()}
	</div>
	<div class="h_100 fixed t_0 l_0" style:width="var(--sidebar_width)">
		<!-- TODO refactor -->
		<div class="h_100 w_100 pt_sm pl_sm" style:width="var(--sidebar_width)">
			<!-- TODO support `max_height_100` in Moss -->
			<nav class="panel column size_lg p_sm overflow_auto" style:max-height="100%">
				<div class="flex mb_sm">
					<Nav_Link
						href="{base}/"
						attrs={{
							title: 'home',
							style: 'width: auto; background: transparent',
							class: 'click_effect_scale',
						}}
					>
						<Svg data={zzz_logo} size="var(--icon_size_md)" />
					</Nav_Link>
				</div>
				<!-- Content -->
				<Nav_Link href="{base}/chats"><span class="icon_xs">{SYMBOL_CHAT}</span> chats</Nav_Link>
				<Nav_Link href="{base}/prompts"
					><span class="icon_xs">{SYMBOL_PROMPTS}</span> prompts</Nav_Link
				>
				<Nav_Link href="{base}/files"><span class="icon_xs">{SYMBOL_FILE}</span> files</Nav_Link>

				<!-- <a href="{base}/pages" class:selected={page.url.pathname === base + '/pages'}>pages</a>
				<a href="{base}/lists" class:selected={page.url.pathname === base + '/lists'}>lists</a>
				<a href="{base}/posts" class:selected={page.url.pathname === base + '/posts'}>posts</a>
				<a href="{base}/cells" class:selected={page.url.pathname === base + '/cells'}>cells</a> OR "data" -->

				<!-- Collaboration -->
				<!-- <h3>Collaboration</h3>
				<a href="{base}/people" class:selected={page.url.pathname === base + '/people'}>people</a>
				<a href="{base}/spaces" class:selected={page.url.pathname === base + '/spaces'}>spaces</a> -->

				<!-- AI Tools -->
				<h3 class="h3_ui">AI</h3>
				<Nav_Link href="{base}/providers"
					><span class="icon_xs">{SYMBOL_PROVIDER}</span> providers</Nav_Link
				>
				<Nav_Link href="{base}/models"><span class="icon_xs">{SYMBOL_MODEL}</span> models</Nav_Link>
				<!-- <a href="{base}/experiments" class:selected={page.url.pathname === base + '/experiments'}
					>experiments</a
				>
				<a href="{base}/providers" class:selected={page.url.pathname === base + '/provider'}>providers</a> -->

				<!-- System -->
				<h3 class="h3_ui">system</h3>
				<Nav_Link href="{base}/about">
					{#snippet children(selected)}<span class="icon_xs"
							><Svg
								data={zzz_logo}
								fill={selected ? 'var(--color_a_6)' : 'var(--text_color_1)'}
								size="var(--icon_size_xs)"
							/></span
						> about{/snippet}</Nav_Link
				>
				<Nav_Link href="{base}/capabilities"
					><span class="icon_xs">{SYMBOL_CAPABILITIES}</span> capabilities</Nav_Link
				>
				<!-- TODO more - terminal, database, account -->
				<Nav_Link href="{base}/settings"
					><span class="icon_xs">{SYMBOL_SETTINGS}</span> settings</Nav_Link
				>

				<!-- Speculative links to add (generated by Claude): -->

				<!-- Core -->
				<!-- <div class="flex mb_sm">
					<Nav_Link
						href="{base}/"
						attrs={{
							title: 'Command Center',
							style: 'width: auto; background: transparent',
							class: 'click_effect_scale',
						}}
					>
						<Svg data={zzz_logo} size="var(--icon_size_md)" />
					</Nav_Link>
				</div> -->

				<!-- Quick Actions -->
				<!-- <h3 class="h3_ui">Quick Actions</h3>
				<Nav_Link href="{base}/new/chat">New Chat</Nav_Link>
				<Nav_Link href="{base}/new/page">New Page</Nav_Link>
				<Nav_Link href="{base}/new/agent">New Agent</Nav_Link>
				<Nav_Link href="{base}/files/browse">Browse Files</Nav_Link> -->

				<!-- Content -->
				<!-- <h3 class="h3_ui">Content</h3>
				<Nav_Link href="{base}/files">Files & Media</Nav_Link>
				<Nav_Link href="{base}/pages">Pages</Nav_Link>
				<Nav_Link href="{base}/lists">Lists</Nav_Link>
				<Nav_Link href="{base}/docs">Documents</Nav_Link>
				<Nav_Link href="{base}/media">Media Library</Nav_Link> -->

				<!-- Communication -->
				<!-- <h3 class="h3_ui">Communication</h3>
				<Nav_Link href="{base}/chats">Chats</Nav_Link>
				<Nav_Link href="{base}/forums">Forums</Nav_Link>
				<Nav_Link href="{base}/spaces">Spaces</Nav_Link>
				<Nav_Link href="{base}/channels">Channels</Nav_Link> -->

				<!-- Intelligence -->
				<!-- <h3 class="h3_ui">Intelligence</h3>
				<Nav_Link href="{base}/agents">Agents</Nav_Link>
				<Nav_Link href="{base}/providers">Providers</Nav_Link>
				<Nav_Link href="{base}/models">Models</Nav_Link>
				<Nav_Link href="{base}/prompts">Prompts</Nav_Link>
				<Nav_Link href="{base}/experiments">Experiments</Nav_Link> -->

				<!-- Development -->
				<!-- <h3 class="h3_ui">Development</h3>
				<Nav_Link href="{base}/plugins">Plugins</Nav_Link>
				<Nav_Link href="{base}/api">API</Nav_Link>
				<Nav_Link href="{base}/terminal">Terminal</Nav_Link>
				<Nav_Link href="{base}/database">Database</Nav_Link> -->

				<!-- Analytics -->
				<!-- <h3 class="h3_ui">Analytics</h3>
				<Nav_Link href="{base}/metrics">Metrics</Nav_Link>
				<Nav_Link href="{base}/usage">Usage</Nav_Link>
				<Nav_Link href="{base}/logs">Logs</Nav_Link> -->

				<!-- Network -->
				<!-- <h3 class="h3_ui">Network</h3>
				<Nav_Link href="{base}/peers">Peers</Nav_Link>
				<Nav_Link href="{base}/federation">Federation</Nav_Link>
				<Nav_Link href="{base}/sync">Sync</Nav_Link> -->

				<!-- System -->
				<!-- <h3 class="h3_ui">System</h3>
				<Nav_Link href="{base}/settings">Settings</Nav_Link>
				<Nav_Link href="{base}/capabilities">Capabilities</Nav_Link>
				<Nav_Link href="{base}/security">Security</Nav_Link>
				<Nav_Link href="{base}/about">About</Nav_Link>
				<Nav_Link href="{base}/status">Status</Nav_Link> -->

				<!-- Even more: -->

				<!-- Command Center -->
				<!-- <div class="flex mb_sm">
					<Nav_Link
						href="{base}/"
						attrs={{
							title: 'Command Center',
							style: 'width: auto; background: transparent',
							class: 'click_effect_scale',
						}}
					>
						<Svg data={zzz_logo} size="var(--icon_size_md)" />
					</Nav_Link>
				</div> -->

				<!-- Quick Actions -->
				<!-- <h3 class="h3_ui">Quick Actions</h3>
				<Nav_Link href="{base}/new/chat">New Chat</Nav_Link>
				<Nav_Link href="{base}/new/page">New Page</Nav_Link>
				<Nav_Link href="{base}/new/agent">New Agent</Nav_Link>
				<Nav_Link href="{base}/new/experiment">New Experiment</Nav_Link>
				<Nav_Link href="{base}/files/browse">Browse Files</Nav_Link>
				<Nav_Link href="{base}/quick/deploy">Quick Deploy</Nav_Link> -->

				<!-- Content Management -->
				<!-- <h3 class="h3_ui">Content</h3>
				<Nav_Link href="{base}/files">Files & Media</Nav_Link>
				<Nav_Link href="{base}/pages">Pages</Nav_Link>
				<Nav_Link href="{base}/lists">Lists</Nav_Link>
				<Nav_Link href="{base}/docs">Documents</Nav_Link>
				<Nav_Link href="{base}/media">Media Library</Nav_Link>
				<Nav_Link href="{base}/templates">Templates</Nav_Link>
				<Nav_Link href="{base}/collections">Collections</Nav_Link>
				<Nav_Link href="{base}/archives">Archives</Nav_Link> -->

				<!-- Communication -->
				<!-- <h3 class="h3_ui">Communication</h3>
				<Nav_Link href="{base}/chats">Chats</Nav_Link>
				<Nav_Link href="{base}/forums">Forums</Nav_Link>
				<Nav_Link href="{base}/spaces">Spaces</Nav_Link>
				<Nav_Link href="{base}/channels">Channels</Nav_Link>
				<Nav_Link href="{base}/discussions">Discussions</Nav_Link>
				<Nav_Link href="{base}/broadcasts">Broadcasts</Nav_Link>
				<Nav_Link href="{base}/messages">Direct Messages</Nav_Link>
				<Nav_Link href="{base}/comments">Comments</Nav_Link>
 -->
				<!-- Intelligence -->
				<!-- <h3 class="h3_ui">Intelligence</h3>
				<Nav_Link href="{base}/agents">Agents</Nav_Link>
				<Nav_Link href="{base}/providers">Providers</Nav_Link>
				<Nav_Link href="{base}/models">Models</Nav_Link>
				<Nav_Link href="{base}/prompts">Prompts</Nav_Link>
				<Nav_Link href="{base}/experiments">Experiments</Nav_Link>
				<Nav_Link href="{base}/training">Training</Nav_Link>
				<Nav_Link href="{base}/datasets">Datasets</Nav_Link>
				<Nav_Link href="{base}/knowledge">Knowledge Base</Nav_Link> -->

				<!-- Automation -->
				<!-- <h3 class="h3_ui">Automation</h3>
				<Nav_Link href="{base}/workflows">Workflows</Nav_Link>
				<Nav_Link href="{base}/tasks">Tasks</Nav_Link>
				<Nav_Link href="{base}/schedules">Schedules</Nav_Link>
				<Nav_Link href="{base}/triggers">Triggers</Nav_Link>
				<Nav_Link href="{base}/actions">Actions</Nav_Link>
				<Nav_Link href="{base}/rules">Rules</Nav_Link> -->

				<!-- Development -->
				<!-- <h3 class="h3_ui">Development</h3>
				<Nav_Link href="{base}/plugins">Plugins</Nav_Link>
				<Nav_Link href="{base}/api">API</Nav_Link>
				<Nav_Link href="{base}/terminal">Terminal</Nav_Link>
				<Nav_Link href="{base}/database">Database</Nav_Link>
				<Nav_Link href="{base}/editor">Code Editor</Nav_Link>
				<Nav_Link href="{base}/debug">Debugger</Nav_Link>
				<Nav_Link href="{base}/testing">Testing</Nav_Link>
				<Nav_Link href="{base}/builds">Builds</Nav_Link> -->

				<!-- Analytics -->
				<!-- <h3 class="h3_ui">Analytics</h3>
				<Nav_Link href="{base}/metrics">Metrics</Nav_Link>
				<Nav_Link href="{base}/usage">Usage</Nav_Link>
				<Nav_Link href="{base}/logs">Logs</Nav_Link>
				<Nav_Link href="{base}/performance">Performance</Nav_Link>
				<Nav_Link href="{base}/insights">Insights</Nav_Link>
				<Nav_Link href="{base}/reports">Reports</Nav_Link> -->

				<!-- Network -->
				<!-- <h3 class="h3_ui">Network</h3>
				<Nav_Link href="{base}/peers">Peers</Nav_Link>
				<Nav_Link href="{base}/federation">Federation</Nav_Link>
				<Nav_Link href="{base}/sync">Sync</Nav_Link>
				<Nav_Link href="{base}/discovery">Discovery</Nav_Link>
				<Nav_Link href="{base}/bridges">Bridges</Nav_Link>
				<Nav_Link href="{base}/gateways">Gateways</Nav_Link> -->

				<!-- Security -->
				<!-- <h3 class="h3_ui">Security</h3>
				<Nav_Link href="{base}/access">Access Control</Nav_Link>
				<Nav_Link href="{base}/encryption">Encryption</Nav_Link>
				<Nav_Link href="{base}/keys">Key Management</Nav_Link>
				<Nav_Link href="{base}/audit">Audit Trails</Nav_Link>
				<Nav_Link href="{base}/backup">Backups</Nav_Link>
				<Nav_Link href="{base}/recovery">Recovery</Nav_Link> -->

				<!-- Collaboration -->
				<!-- <h3 class="h3_ui">Collaboration</h3>
				<Nav_Link href="{base}/teams">Teams</Nav_Link>
				<Nav_Link href="{base}/projects">Projects</Nav_Link>
				<Nav_Link href="{base}/sharing">Sharing</Nav_Link>
				<Nav_Link href="{base}/permissions">Permissions</Nav_Link>
				<Nav_Link href="{base}/roles">Roles</Nav_Link>
				<Nav_Link href="{base}/invites">Invites</Nav_Link> -->

				<!-- System -->
				<!-- <h3 class="h3_ui">System</h3>
				<Nav_Link href="{base}/settings">Settings</Nav_Link>
				<Nav_Link href="{base}/capabilities">Capabilities</Nav_Link>
				<Nav_Link href="{base}/resources">Resources</Nav_Link>
				<Nav_Link href="{base}/storage">Storage</Nav_Link>
				<Nav_Link href="{base}/updates">Updates</Nav_Link>
				<Nav_Link href="{base}/status">Status</Nav_Link>
				<Nav_Link href="{base}/about">About</Nav_Link>
				<Nav_Link href="{base}/help">Help</Nav_Link> -->
			</nav>
		</div>
	</div>
</div>
