// generated by src/lib/frontend_action_types.gen.ts - DO NOT EDIT OR RISK LOST DATA

import type {Action_Event} from '$lib/action_event.js';
import type {Frontend} from '$lib/frontend.svelte.js';
import type {Action_Outputs} from '$lib/action_collections.js';

/**
 * Frontend action handlers organized by method and phase.
 * Generated using spec.initiator to determine valid phases:
 * - initiator: 'frontend' → send/execute phases
 * - initiator: 'backend' → receive phases
 * - initiator: 'both' → all valid phases
 */
export interface Frontend_Action_Handlers {
	completion_progress?: {
		receive?: (
			action_event: Action_Event<'completion_progress', Frontend, 'receive', 'handling'>,
		) => void | Promise<void>;
	};
	create_completion?: {
		send_request?: (
			action_event: Action_Event<'create_completion', Frontend, 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: Action_Event<'create_completion', Frontend, 'receive_response', 'handling'>,
		) => void | Promise<void>;
	};
	create_directory?: {
		send_request?: (
			action_event: Action_Event<'create_directory', Frontend, 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: Action_Event<'create_directory', Frontend, 'receive_response', 'handling'>,
		) => void | Promise<void>;
	};
	delete_diskfile?: {
		send_request?: (
			action_event: Action_Event<'delete_diskfile', Frontend, 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: Action_Event<'delete_diskfile', Frontend, 'receive_response', 'handling'>,
		) => void | Promise<void>;
	};
	filer_change?: {
		receive?: (
			action_event: Action_Event<'filer_change', Frontend, 'receive', 'handling'>,
		) => void | Promise<void>;
	};
	load_session?: {
		send_request?: (
			action_event: Action_Event<'load_session', Frontend, 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: Action_Event<'load_session', Frontend, 'receive_response', 'handling'>,
		) => void | Promise<void>;
	};
	ollama_copy?: {
		send_request?: (
			action_event: Action_Event<'ollama_copy', Frontend, 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: Action_Event<'ollama_copy', Frontend, 'receive_response', 'handling'>,
		) => void | Promise<void>;
	};
	ollama_create?: {
		send_request?: (
			action_event: Action_Event<'ollama_create', Frontend, 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: Action_Event<'ollama_create', Frontend, 'receive_response', 'handling'>,
		) => void | Promise<void>;
	};
	ollama_delete?: {
		send_request?: (
			action_event: Action_Event<'ollama_delete', Frontend, 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: Action_Event<'ollama_delete', Frontend, 'receive_response', 'handling'>,
		) => void | Promise<void>;
	};
	ollama_list?: {
		send_request?: (
			action_event: Action_Event<'ollama_list', Frontend, 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: Action_Event<'ollama_list', Frontend, 'receive_response', 'handling'>,
		) => void | Promise<void>;
	};
	ollama_progress?: {
		receive?: (
			action_event: Action_Event<'ollama_progress', Frontend, 'receive', 'handling'>,
		) => void | Promise<void>;
	};
	ollama_ps?: {
		send_request?: (
			action_event: Action_Event<'ollama_ps', Frontend, 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: Action_Event<'ollama_ps', Frontend, 'receive_response', 'handling'>,
		) => void | Promise<void>;
	};
	ollama_pull?: {
		send_request?: (
			action_event: Action_Event<'ollama_pull', Frontend, 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: Action_Event<'ollama_pull', Frontend, 'receive_response', 'handling'>,
		) => void | Promise<void>;
	};
	ollama_show?: {
		send_request?: (
			action_event: Action_Event<'ollama_show', Frontend, 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: Action_Event<'ollama_show', Frontend, 'receive_response', 'handling'>,
		) => void | Promise<void>;
	};
	ollama_unload?: {
		send_request?: (
			action_event: Action_Event<'ollama_unload', Frontend, 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: Action_Event<'ollama_unload', Frontend, 'receive_response', 'handling'>,
		) => void | Promise<void>;
	};
	ping?: {
		send_request?: (
			action_event: Action_Event<'ping', Frontend, 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: Action_Event<'ping', Frontend, 'receive_response', 'handling'>,
		) => void | Promise<void>;
		receive_request?: (
			action_event: Action_Event<'ping', Frontend, 'receive_request', 'handling'>,
		) => Action_Outputs['ping'] | Promise<Action_Outputs['ping']>;
		send_response?: (
			action_event: Action_Event<'ping', Frontend, 'send_response', 'handling'>,
		) => void | Promise<void>;
	};
	toggle_main_menu?: {
		execute?: (
			action_event: Action_Event<'toggle_main_menu', Frontend, 'execute', 'handling'>,
		) => Action_Outputs['toggle_main_menu'];
	};
	update_diskfile?: {
		send_request?: (
			action_event: Action_Event<'update_diskfile', Frontend, 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: Action_Event<'update_diskfile', Frontend, 'receive_response', 'handling'>,
		) => void | Promise<void>;
	};
}

// generated by src/lib/frontend_action_types.gen.ts - DO NOT EDIT OR RISK LOST DATA
