// generated by src/lib/frontend_action_types.gen.ts - DO NOT EDIT OR RISK LOST DATA

import type {Action_Method} from '$lib/action_metatypes.js';
import type {Action_Inputs, Action_Outputs} from '$lib/action_collections.js';
import type {
	Frontend_Request_Response_Action_Event,
	Frontend_Remote_Notification_Action_Event,
	Frontend_Local_Call_Action_Event,
} from '$lib/frontend_action_event.js';

/**
 * Frontend action handlers organized by method and phase.
 * Generated using spec.initiator to determine valid phases:
 * - initiator: 'frontend' → send/execute phases
 * - initiator: 'backend' → receive phases
 * - initiator: 'both' → all valid phases
 */
export interface Frontend_Action_Handlers {
	create_directory?: {
		send_request?: (
			action_event: Frontend_Request_Response_Action_Event<
				'create_directory',
				Action_Inputs['create_directory'],
				Action_Outputs['create_directory']
			>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: Frontend_Request_Response_Action_Event<
				'create_directory',
				Action_Inputs['create_directory'],
				Action_Outputs['create_directory']
			>,
		) => void | Promise<void>;
	};
	delete_diskfile?: {
		send_request?: (
			action_event: Frontend_Request_Response_Action_Event<
				'delete_diskfile',
				Action_Inputs['delete_diskfile'],
				Action_Outputs['delete_diskfile']
			>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: Frontend_Request_Response_Action_Event<
				'delete_diskfile',
				Action_Inputs['delete_diskfile'],
				Action_Outputs['delete_diskfile']
			>,
		) => void | Promise<void>;
	};
	filer_change?: {
		receive?: (
			action_event: Frontend_Remote_Notification_Action_Event<
				'filer_change',
				Action_Inputs['filer_change']
			>,
		) => void | Promise<void>;
	};
	load_session?: {
		send_request?: (
			action_event: Frontend_Request_Response_Action_Event<
				'load_session',
				Action_Inputs['load_session'],
				Action_Outputs['load_session']
			>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: Frontend_Request_Response_Action_Event<
				'load_session',
				Action_Inputs['load_session'],
				Action_Outputs['load_session']
			>,
		) => void | Promise<void>;
	};
	ping?: {
		send_request?: (
			action_event: Frontend_Request_Response_Action_Event<
				'ping',
				Action_Inputs['ping'],
				Action_Outputs['ping']
			>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: Frontend_Request_Response_Action_Event<
				'ping',
				Action_Inputs['ping'],
				Action_Outputs['ping']
			>,
		) => void | Promise<void>;
		receive_request?: (
			action_event: Frontend_Request_Response_Action_Event<
				'ping',
				Action_Inputs['ping'],
				Action_Outputs['ping']
			>,
		) => Action_Outputs['ping'] | Promise<Action_Outputs['ping']>;
		send_response?: (
			action_event: Frontend_Request_Response_Action_Event<
				'ping',
				Action_Inputs['ping'],
				Action_Outputs['ping']
			>,
		) => void | Promise<void>;
	};
	submit_completion?: {
		send_request?: (
			action_event: Frontend_Request_Response_Action_Event<
				'submit_completion',
				Action_Inputs['submit_completion'],
				Action_Outputs['submit_completion']
			>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: Frontend_Request_Response_Action_Event<
				'submit_completion',
				Action_Inputs['submit_completion'],
				Action_Outputs['submit_completion']
			>,
		) => void | Promise<void>;
	};
	toggle_main_menu?: {
		execute?: (
			action_event: Frontend_Local_Call_Action_Event<
				'toggle_main_menu',
				Action_Inputs['toggle_main_menu'],
				Action_Outputs['toggle_main_menu']
			>,
		) => Action_Outputs['toggle_main_menu'];
	};
	update_diskfile?: {
		send_request?: (
			action_event: Frontend_Request_Response_Action_Event<
				'update_diskfile',
				Action_Inputs['update_diskfile'],
				Action_Outputs['update_diskfile']
			>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: Frontend_Request_Response_Action_Event<
				'update_diskfile',
				Action_Inputs['update_diskfile'],
				Action_Outputs['update_diskfile']
			>,
		) => void | Promise<void>;
	};
}

// generated by src/lib/frontend_action_types.gen.ts - DO NOT EDIT OR RISK LOST DATA
