// generated by src/lib/server/backend_action_types.gen.ts - DO NOT EDIT OR RISK LOST DATA

import type {Action_Event} from '$lib/action_event.js';
import type {Backend} from '$lib/server/backend.js';
import type {Action_Outputs} from '$lib/action_collections.js';

/**
 * Backend action handlers organized by method and phase.
 * Generated using spec.initiator to determine valid phases:
 * - initiator: 'backend' → send/execute phases
 * - initiator: 'frontend' → receive phases
 * - initiator: 'both' → all valid phases
 */
export interface Backend_Action_Handlers {
	create_directory?: {
		receive_request?: (
			action_event: Action_Event<'create_directory', Backend, 'receive_request', 'handling'>,
		) => Action_Outputs['create_directory'] | Promise<Action_Outputs['create_directory']>;
		send_response?: (
			action_event: Action_Event<'create_directory', Backend, 'send_response', 'handling'>,
		) => void | Promise<void>;
	};
	delete_diskfile?: {
		receive_request?: (
			action_event: Action_Event<'delete_diskfile', Backend, 'receive_request', 'handling'>,
		) => Action_Outputs['delete_diskfile'] | Promise<Action_Outputs['delete_diskfile']>;
		send_response?: (
			action_event: Action_Event<'delete_diskfile', Backend, 'send_response', 'handling'>,
		) => void | Promise<void>;
	};
	filer_change?: {
		send?: (
			action_event: Action_Event<'filer_change', Backend, 'send', 'handling'>,
		) => void | Promise<void>;
	};
	load_session?: {
		receive_request?: (
			action_event: Action_Event<'load_session', Backend, 'receive_request', 'handling'>,
		) => Action_Outputs['load_session'] | Promise<Action_Outputs['load_session']>;
		send_response?: (
			action_event: Action_Event<'load_session', Backend, 'send_response', 'handling'>,
		) => void | Promise<void>;
	};
	ping?: {
		send_request?: (
			action_event: Action_Event<'ping', Backend, 'send_request', 'handling'>,
		) => void | Promise<void>;
		receive_response?: (
			action_event: Action_Event<'ping', Backend, 'receive_response', 'handling'>,
		) => void | Promise<void>;
		receive_request?: (
			action_event: Action_Event<'ping', Backend, 'receive_request', 'handling'>,
		) => Action_Outputs['ping'] | Promise<Action_Outputs['ping']>;
		send_response?: (
			action_event: Action_Event<'ping', Backend, 'send_response', 'handling'>,
		) => void | Promise<void>;
	};
	submit_completion?: {
		receive_request?: (
			action_event: Action_Event<'submit_completion', Backend, 'receive_request', 'handling'>,
		) => Action_Outputs['submit_completion'] | Promise<Action_Outputs['submit_completion']>;
		send_response?: (
			action_event: Action_Event<'submit_completion', Backend, 'send_response', 'handling'>,
		) => void | Promise<void>;
	};
	toggle_main_menu?: never;
	update_diskfile?: {
		receive_request?: (
			action_event: Action_Event<'update_diskfile', Backend, 'receive_request', 'handling'>,
		) => Action_Outputs['update_diskfile'] | Promise<Action_Outputs['update_diskfile']>;
		send_response?: (
			action_event: Action_Event<'update_diskfile', Backend, 'send_response', 'handling'>,
		) => void | Promise<void>;
	};
}

// generated by src/lib/server/backend_action_types.gen.ts - DO NOT EDIT OR RISK LOST DATA
