// generated by src/lib/server/backend_action_types.gen.ts - DO NOT EDIT OR RISK LOST DATA

import type {Action_Event} from '$lib/action_event.js';
import type {Action_Event_Datas, Action_Outputs} from '$lib/action_collections.js';
import type {Zzz_Server} from '$lib/server/zzz_server.js';

/**
 * Backend action handlers organized by method and phase.
 * Generated using spec.initiator to determine valid phases:
 * - initiator: 'backend' → send/execute phases
 * - initiator: 'frontend' → receive phases
 * - initiator: 'both' → all valid phases
 */
export interface Backend_Action_Handlers {
	create_directory?: {
		receive_request?: (
			action_event: Action_Event<'create_directory', Zzz_Server> & {
				data: Extract<
					Action_Event_Datas['create_directory'],
					{phase: 'receive_request'; step: 'handling'}
				>;
			},
		) => Action_Outputs['create_directory'] | Promise<Action_Outputs['create_directory']>;
		send_response?: (
			action_event: Action_Event<'create_directory', Zzz_Server> & {
				data: Extract<
					Action_Event_Datas['create_directory'],
					{phase: 'send_response'; step: 'handling'}
				>;
			},
		) => void | Promise<void>;
	};
	delete_diskfile?: {
		receive_request?: (
			action_event: Action_Event<'delete_diskfile', Zzz_Server> & {
				data: Extract<
					Action_Event_Datas['delete_diskfile'],
					{phase: 'receive_request'; step: 'handling'}
				>;
			},
		) => Action_Outputs['delete_diskfile'] | Promise<Action_Outputs['delete_diskfile']>;
		send_response?: (
			action_event: Action_Event<'delete_diskfile', Zzz_Server> & {
				data: Extract<
					Action_Event_Datas['delete_diskfile'],
					{phase: 'send_response'; step: 'handling'}
				>;
			},
		) => void | Promise<void>;
	};
	filer_change?: {
		send?: (
			action_event: Action_Event<'filer_change', Zzz_Server> & {
				data: Extract<Action_Event_Datas['filer_change'], {phase: 'send'; step: 'handling'}>;
			},
		) => void | Promise<void>;
	};
	load_session?: {
		receive_request?: (
			action_event: Action_Event<'load_session', Zzz_Server> & {
				data: Extract<
					Action_Event_Datas['load_session'],
					{phase: 'receive_request'; step: 'handling'}
				>;
			},
		) => Action_Outputs['load_session'] | Promise<Action_Outputs['load_session']>;
		send_response?: (
			action_event: Action_Event<'load_session', Zzz_Server> & {
				data: Extract<
					Action_Event_Datas['load_session'],
					{phase: 'send_response'; step: 'handling'}
				>;
			},
		) => void | Promise<void>;
	};
	ping?: {
		send_request?: (
			action_event: Action_Event<'ping', Zzz_Server> & {
				data: Extract<Action_Event_Datas['ping'], {phase: 'send_request'; step: 'handling'}>;
			},
		) => void | Promise<void>;
		receive_response?: (
			action_event: Action_Event<'ping', Zzz_Server> & {
				data: Extract<Action_Event_Datas['ping'], {phase: 'receive_response'; step: 'handling'}>;
			},
		) => void | Promise<void>;
		receive_request?: (
			action_event: Action_Event<'ping', Zzz_Server> & {
				data: Extract<Action_Event_Datas['ping'], {phase: 'receive_request'; step: 'handling'}>;
			},
		) => Action_Outputs['ping'] | Promise<Action_Outputs['ping']>;
		send_response?: (
			action_event: Action_Event<'ping', Zzz_Server> & {
				data: Extract<Action_Event_Datas['ping'], {phase: 'send_response'; step: 'handling'}>;
			},
		) => void | Promise<void>;
	};
	submit_completion?: {
		receive_request?: (
			action_event: Action_Event<'submit_completion', Zzz_Server> & {
				data: Extract<
					Action_Event_Datas['submit_completion'],
					{phase: 'receive_request'; step: 'handling'}
				>;
			},
		) => Action_Outputs['submit_completion'] | Promise<Action_Outputs['submit_completion']>;
		send_response?: (
			action_event: Action_Event<'submit_completion', Zzz_Server> & {
				data: Extract<
					Action_Event_Datas['submit_completion'],
					{phase: 'send_response'; step: 'handling'}
				>;
			},
		) => void | Promise<void>;
	};
	toggle_main_menu?: never;
	update_diskfile?: {
		receive_request?: (
			action_event: Action_Event<'update_diskfile', Zzz_Server> & {
				data: Extract<
					Action_Event_Datas['update_diskfile'],
					{phase: 'receive_request'; step: 'handling'}
				>;
			},
		) => Action_Outputs['update_diskfile'] | Promise<Action_Outputs['update_diskfile']>;
		send_response?: (
			action_event: Action_Event<'update_diskfile', Zzz_Server> & {
				data: Extract<
					Action_Event_Datas['update_diskfile'],
					{phase: 'send_response'; step: 'handling'}
				>;
			},
		) => void | Promise<void>;
	};
}

// generated by src/lib/server/backend_action_types.gen.ts - DO NOT EDIT OR RISK LOST DATA
