// @slop
// server/backend_action_types.gen.ts

import type {Gen} from '@ryanatkn/gro/gen.js';

import {action_specs} from '$lib/action_collections.js';
import {Action_Registry} from '$lib/action_registry.js';
import type {Action_Phase} from '$lib/action_types.js';
import type {Action_Spec} from '$lib/action_spec.js';

/**
 * Generates backend action handler types based on spec.initiator.
 * Backend can handle:
 * - send/execute phases when initiator is 'backend' or 'both'
 * - receive phases when initiator is 'frontend' or 'both'
 */
export const gen: Gen = ({origin_path}) => {
	const registry = new Action_Registry(action_specs);

	const banner = `generated by ${origin_path} - DO NOT EDIT OR RISK LOST DATA`;

	// Determine which action event types are needed
	const needs_request_response = registry.specs.some((spec) => spec.kind === 'request_response');
	const needs_remote_notification = registry.specs.some(
		(spec) => spec.kind === 'remote_notification',
	);
	const needs_local_call = registry.specs.some((spec) => spec.kind === 'local_call');

	const action_event_imports = [];
	if (needs_request_response) action_event_imports.push('Backend_Request_Response_Action_Event');
	if (needs_remote_notification)
		action_event_imports.push('Backend_Remote_Notification_Action_Event');
	if (needs_local_call) action_event_imports.push('Backend_Local_Call_Action_Event');

	const backend_action_handlers = registry.specs
		.map((s) => generate_backend_phase_handlers(s))
		.join(';\n\t');

	return `
		// ${banner}

		import type {Action_Inputs, Action_Outputs} from '$lib/action_collections.js';
		import type {${action_event_imports.join(', ')}} from '$lib/server/backend_action_event.js';

		/**
		 * Backend action handlers organized by method and phase.
		 * Generated using spec.initiator to determine valid phases:
		 * - initiator: 'backend' → send/execute phases
		 * - initiator: 'frontend' → receive phases
		 * - initiator: 'both' → all valid phases
		 */
		export interface Backend_Action_Handlers {
			${backend_action_handlers}
		}

		// ${banner}
	`;
};

const generate_backend_phase_handlers = (spec: Action_Spec): string => {
	const {method, kind, initiator} = spec;

	// Determine which phases backend can handle based on initiator
	const backend_phases: Array<Action_Phase> = [];

	if (kind === 'request_response') {
		if (initiator === 'backend' || initiator === 'both') {
			backend_phases.push('send_request', 'receive_response');
		}
		if (initiator === 'frontend' || initiator === 'both') {
			backend_phases.push('receive_request', 'send_response');
		}
	} else if (kind === 'remote_notification') {
		if (initiator === 'backend' || initiator === 'both') {
			backend_phases.push('send');
		}
		if (initiator === 'frontend' || initiator === 'both') {
			backend_phases.push('receive');
		}
		// eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
	} else if (kind === 'local_call') {
		if (initiator === 'backend' || initiator === 'both') {
			backend_phases.push('execute');
		}
	}

	if (backend_phases.length === 0) {
		return `${method}?: never`;
	}

	// Determine the action event type
	let event_type: string;
	if (kind === 'request_response') {
		event_type = `Backend_Request_Response_Action_Event<'${method}', Action_Inputs['${method}'], Action_Outputs['${method}']>`;
	} else if (kind === 'remote_notification') {
		event_type = `Backend_Remote_Notification_Action_Event<'${method}', Action_Inputs['${method}']>`;
	} else {
		event_type = `Backend_Local_Call_Action_Event<'${method}', Action_Inputs['${method}'], Action_Outputs['${method}']>`;
	}

	const phase_handlers = backend_phases
		.map((phase: Action_Phase) => {
			const return_type = get_handler_return_type(spec, phase);
			return `${phase}?: (action_event: ${event_type}) => ${return_type}`;
		})
		.join(';\n\t\t');

	return `${method}?: {\n\t\t${phase_handlers};\n\t}`;
};

const get_handler_return_type = (spec: Action_Spec, phase: Action_Phase): string => {
	// For request_response receive_request, handler returns the output
	if (spec.kind === 'request_response' && phase === 'receive_request') {
		const base_type = `Action_Outputs['${spec.method}']`;
		return `${base_type} | Promise<${base_type}>`;
	}

	// For local_call execute, handler returns the output
	if (spec.kind === 'local_call' && phase === 'execute') {
		const base_type = `Action_Outputs['${spec.method}']`;
		return spec.async ? `${base_type} | Promise<${base_type}>` : base_type;
	}

	// All other phases return void
	return spec.async ? 'void | Promise<void>' : 'void';
};
