// generated by src/lib/server/server_action_metatypes.gen.ts - DO NOT EDIT OR RISK LOST DATA

import type {Public_Server_Action_Handler} from '$lib/server/server_action_handler.js';
import type {
	create_directory_action_spec,
	delete_diskfile_action_spec,
	load_session_action_spec,
	ping_action_spec,
	submit_completion_action_spec,
	update_diskfile_action_spec,
} from '$lib/action_specs.js';
import type {Action_Messages} from '$lib/action_messages.js';

/**
 * Maps action names to their service implementations.
 */
export interface Server_Action_Handlers {
	create_directory: Public_Server_Action_Handler<
		typeof create_directory_action_spec.input,
		typeof create_directory_action_spec.output,
		Action_Messages['create_directory_request']
	>;
	delete_diskfile: Public_Server_Action_Handler<
		typeof delete_diskfile_action_spec.input,
		typeof delete_diskfile_action_spec.output,
		Action_Messages['delete_diskfile_request']
	>;
	load_session: Public_Server_Action_Handler<
		typeof load_session_action_spec.input,
		typeof load_session_action_spec.output,
		Action_Messages['load_session_request']
	>;
	ping: Public_Server_Action_Handler<
		typeof ping_action_spec.input,
		typeof ping_action_spec.output,
		Action_Messages['ping_request']
	>;
	submit_completion: Public_Server_Action_Handler<
		typeof submit_completion_action_spec.input,
		typeof submit_completion_action_spec.output,
		Action_Messages['submit_completion_request']
	>;
	update_diskfile: Public_Server_Action_Handler<
		typeof update_diskfile_action_spec.input,
		typeof update_diskfile_action_spec.output,
		Action_Messages['update_diskfile_request']
	>;
}

// generated by src/lib/server/server_action_metatypes.gen.ts - DO NOT EDIT OR RISK LOST DATA
