import type {Gen} from '@ryanatkn/gro/gen.js';

import {
	to_action_spec_identifier,
	to_action_spec_response_params_identifier,
} from '$lib/schema_helpers.js';
import {action_specs} from '$lib/action_collections.js';
import {Action_Registry} from '$lib/action_registry.js';

/**
 * Outputs a file with service types that can be imported from anywhere with no runtime cost.
 */
export const gen: Gen = ({origin_path}) => {
	const registry = new Action_Registry(action_specs);

	// Get only the schema names for request_response actions
	const request_response_specs = registry.request_response_specs;
	const schema_imports = request_response_specs.map((spec) => `${spec.method}_action_spec`);

	// Determine which service types are needed based on auth requirements
	const needs_nonauthenticated = request_response_specs.some((spec) => spec.auth === null);
	const needs_nonauthorized = request_response_specs.some((spec) => spec.auth === 'authenticate');
	const needs_authorized = request_response_specs.some((spec) => spec.auth === 'authorize');

	// Create imports based on what's needed
	const service_imports = [];
	if (needs_nonauthenticated) service_imports.push('Nonauthenticated_Service');
	if (needs_nonauthorized) service_imports.push('Nonauthorized_Service');
	if (needs_authorized) service_imports.push('Authorized_Service');

	const banner = `generated by ${origin_path} - DO NOT EDIT OR RISK LOST DATA`;

	return `
    // ${banner}

    import type {${service_imports.join(', ')}} from '$lib/server/service.js';
    import type {${schema_imports.join(', ')}} from '$lib/action_specs.js';

    /**
     * Maps action names to their service implementations.
     */
    export interface Service_By_Name {
      ${request_response_specs
				.map((spec) => {
					const service_type =
						spec.auth === null
							? 'Nonauthenticated_Service'
							: spec.auth === 'authenticate'
								? 'Nonauthorized_Service'
								: 'Authorized_Service';

					return `${spec.method}: ${service_type}<typeof ${to_action_spec_identifier(spec.method)}, typeof ${to_action_spec_response_params_identifier(spec.method)}>;`;
				})
				.join('\n\t')}
    }

    // ${banner}
  `;
};
