// generated by src/lib/server/service_metatypes.gen.ts - DO NOT EDIT OR RISK LOST DATA

import type {Nonauthenticated_Service} from '$lib/server/service.js';
import type {
	create_directory_action_spec,
	delete_diskfile_action_spec,
	load_session_action_spec,
	ping_action_spec,
	submit_completion_action_spec,
	update_diskfile_action_spec,
} from '$lib/action_specs.js';

/**
 * Maps action names to their service implementations.
 */
export interface Service_By_Name {
	create_directory: Nonauthenticated_Service<
		typeof create_directory_action_spec,
		typeof create_directory_action_spec.response_params
	>;
	delete_diskfile: Nonauthenticated_Service<
		typeof delete_diskfile_action_spec,
		typeof delete_diskfile_action_spec.response_params
	>;
	load_session: Nonauthenticated_Service<
		typeof load_session_action_spec,
		typeof load_session_action_spec.response_params
	>;
	ping: Nonauthenticated_Service<typeof ping_action_spec, typeof ping_action_spec.response_params>;
	submit_completion: Nonauthenticated_Service<
		typeof submit_completion_action_spec,
		typeof submit_completion_action_spec.response_params
	>;
	update_diskfile: Nonauthenticated_Service<
		typeof update_diskfile_action_spec,
		typeof update_diskfile_action_spec.response_params
	>;
}

// generated by src/lib/server/service_metatypes.gen.ts - DO NOT EDIT OR RISK LOST DATA
