import type {Gen} from '@ryanatkn/gro/gen.js';
import {Unreachable_Error} from '@ryanatkn/belt/error.js';

import {
	to_action_spec_auth_identifier,
	to_action_spec_input_identifier,
	to_action_spec_output_identifier,
} from '$lib/action_helpers.js';
import {action_specs} from '$lib/action_collections.js';
import {Action_Registry} from '$lib/action_registry.js';
import {ACTION_KIND_PHASES, type Action_Phase} from '$lib/action_types.js';
import type {Action_Spec} from '$lib/action_spec.js';

/**
 * Outputs a file with service types that can be imported from anywhere with no runtime cost.
 */
export const gen: Gen = ({origin_path}) => {
	const registry = new Action_Registry(action_specs);

	// Get all specs that could have server handlers
	const schema_imports = registry.specs.map((spec) => `${spec.method}_action_spec`);

	// Determine which service types are needed based on auth requirements
	const needs_public = registry.specs.some((spec) => spec.auth === 'public' || spec.auth === null);
	const needs_authorized = registry.specs.some((spec) => spec.auth === 'authorize');

	// Create imports based on what's needed
	const service_imports = [];
	if (needs_public) service_imports.push('Public_Server_Action_Handler');
	if (needs_authorized) service_imports.push('Authorized_Server_Action_Handler');

	const banner = `generated by ${origin_path} - DO NOT EDIT OR RISK LOST DATA`;

	// Data-driven phase handler generation
	const generate_server_phase_handlers = (spec: Action_Spec): string => {
		const {method, kind, auth} = spec;
		const phases = ACTION_KIND_PHASES[kind];
		const auth_handler = to_action_spec_auth_identifier(auth || 'public');

		const phase_handlers = phases
			.map((phase: Action_Phase) => {
				// Determine input, output, and message types based on phase
				let input_type: string;
				let output_type: string;

				switch (phase) {
					case 'send_request':
						input_type = `z.infer<typeof ${to_action_spec_input_identifier(method)}>`;
						output_type = 'void';

						break;
					case 'receive_request':
						input_type = `z.infer<typeof ${to_action_spec_input_identifier(method)}>`;
						output_type =
							kind === 'request_response'
								? `z.infer<typeof ${to_action_spec_output_identifier(method)}>`
								: 'void';
						break;
					case 'send_response':
						input_type =
							kind === 'request_response'
								? `z.infer<typeof ${to_action_spec_output_identifier(method)}>`
								: 'never';
						output_type = 'void';
						break;
					case 'receive_response':
						input_type =
							kind === 'request_response'
								? `z.infer<typeof ${to_action_spec_output_identifier(method)}>`
								: 'never';
						output_type = 'void';
						break;
					case 'send':
					case 'receive':
						input_type = `z.infer<typeof ${to_action_spec_input_identifier(method)}>`;
						output_type = 'void';
						break;
					case 'execute':
						input_type = `z.infer<typeof ${to_action_spec_input_identifier(method)}>`;
						output_type = spec.returns || 'void';
						break;
					default:
						throw new Unreachable_Error(phase);
				}

				return `${phase}?: ${auth_handler}<
			${input_type},
			${output_type}
		>`;
			})
			.join(';\n\t\t');

		return `${method}?: {\n\t\t${phase_handlers};\n\t}`;
	};

	return `
    // ${banner}

		import type {z} from 'zod';

    import type {${service_imports.join(', ')}} from '$lib/server/server_action_handler.js';
    import type {${schema_imports.join(', ')}} from '$lib/action_specs.js';
		import type {Action_Messages} from '$lib/action_messages.js';

    /**
     * Maps action methods to their server-side phase handlers.
     * Generated using ACTION_KIND_PHASES for consistent phase handling across all action kinds.
     */
    export interface Server_Action_Handlers {
      ${registry.specs.map(generate_server_phase_handlers).join(';\n\t')}
    }

    // ${banner}
  `;
};
