import type {Gen} from '@ryanatkn/gro/gen.js';

import {
	to_action_message_identifier,
	to_action_message_type,
	to_action_spec_auth_identifier,
	to_action_spec_identifier,
	to_action_spec_response_params_identifier,
} from '$lib/action_helpers.js';
import {action_specs} from '$lib/action_collections.js';
import {Action_Registry} from '$lib/action_registry.js';

/**
 * Outputs a file with service types that can be imported from anywhere with no runtime cost.
 */
export const gen: Gen = ({origin_path}) => {
	const registry = new Action_Registry(action_specs);

	// Get only the schema names for request_response actions
	const request_response_specs = registry.request_response_specs;
	const schema_imports = request_response_specs.map((spec) => `${spec.method}_action_spec`);

	// Determine which service types are needed based on auth requirements
	const needs_public = request_response_specs.some((spec) => spec.auth === 'public');
	const needs_authenticated = request_response_specs.some((spec) => spec.auth === 'authenticate');
	const needs_authorized = request_response_specs.some((spec) => spec.auth === 'authorize');

	// Create imports based on what's needed
	const service_imports = [];
	if (needs_public) service_imports.push('Public_Server_Action_Handler');
	if (needs_authenticated) service_imports.push('Authenticated_Server_Action_Handler');
	if (needs_authorized) service_imports.push('Authorized_Server_Action_Handler');

	const banner = `generated by ${origin_path} - DO NOT EDIT OR RISK LOST DATA`;

	return `
    // ${banner}

    import type {${service_imports.join(', ')}} from '$lib/server/server_action_handler.js';
    import type {${schema_imports.join(', ')}} from '$lib/action_specs.js';
		import type {Action_Messages} from '$lib/action_messages.js';

    /**
     * Maps action names to their service implementations.
     */
    export interface Server_Action_Handlers {
      ${
				// TODO BLOCK @api also needs to include server notification actions like filer_change.
				// see too about bidirectional request/response actions so the server can initiate requests, controlled by the client.

				request_response_specs
					.map((spec) => {
						// TODO BLOCK @api handle response messages too, probably rethinking the spec fields like having source/target/phase
						const message_type = to_action_message_type(spec.method, 'request');
						return `${spec.method}: ${to_action_spec_auth_identifier(spec.auth)}<
							typeof ${to_action_spec_identifier(spec.method)},
							typeof ${to_action_spec_response_params_identifier(spec.method)},
							${to_action_message_identifier(message_type)},
						>;`;
					})
					.join('\n\t')
			}
    }

    // ${banner}
  `;
};
