import type {Gen} from '@ryanatkn/gro/gen.js';
import {Unreachable_Error} from '@ryanatkn/belt/error.js';

import {action_specs} from '$lib/action_collections.js';
import {Action_Registry} from '$lib/action_registry.js';
import {ACTION_KIND_PHASES, type Action_Phase} from '$lib/action_types.js';
import type {Action_Spec} from '$lib/action_spec.js';

/**
 * Outputs a file with service types that can be imported from anywhere with no runtime cost.
 */
export const gen: Gen = ({origin_path}) => {
	const registry = new Action_Registry(action_specs);

	const {server_specs} = registry;

	// Determine which handler types are needed based on auth requirements
	const needs_public_request = server_specs.some(
		(spec) => spec.kind === 'request_response' && (spec.auth === 'public' || spec.auth === null),
	);
	const needs_authorized_request = server_specs.some(
		(spec) => spec.kind === 'request_response' && spec.auth === 'authorize',
	);
	const needs_public_notification = server_specs.some(
		(spec) => spec.kind === 'remote_notification' && (spec.auth === 'public' || spec.auth === null),
	);
	const needs_authorized_notification = server_specs.some(
		(spec) => spec.kind === 'remote_notification' && spec.auth === 'authorize',
	);

	// Create imports based on what's needed
	const handler_imports = [];
	if (needs_public_request) handler_imports.push('Public_Server_Request_Handler');
	if (needs_authorized_request) handler_imports.push('Authorized_Server_Request_Handler');
	if (needs_public_notification) handler_imports.push('Public_Server_Notification_Handler');
	if (needs_authorized_notification) handler_imports.push('Authorized_Server_Notification_Handler');

	const banner = `generated by ${origin_path} - DO NOT EDIT OR RISK LOST DATA`;

	// TODO improve this API with a more generic approach to collecting imports
	const collection_imports: Set<string> = new Set();

	const server_action_handlers = server_specs
		.map((s) => generate_server_phase_handlers(s, collection_imports))
		.join(';\n\t');

	return `
    // ${banner}

		import type {${handler_imports.join(', ')}} from '$lib/server/server_action_handler.js';
		${collection_imports.size ? `import type {${Array.from(collection_imports).join(', ')}} from '$lib/action_collections.js';` : ''}

		/**
		 * Maps action methods to their server-side phase handlers.
		 * Generated using ACTION_KIND_PHASES for consistent phase handling across all action kinds.
		 */
		export interface Server_Action_Handlers {
			${server_action_handlers}
		}

		// ${banner}
	`;
};

// Data-driven phase handler generation
const generate_server_phase_handlers = (
	spec: Action_Spec,
	collection_imports: Set<string>,
): string => {
	const {method, kind, auth} = spec;
	const phases = ACTION_KIND_PHASES[kind];

	// Determine handler type based on kind and auth
	let handler_type: string;
	if (kind === 'request_response') {
		handler_type =
			auth === 'authorize' ? 'Authorized_Server_Request_Handler' : 'Public_Server_Request_Handler';
	} else if (kind === 'remote_notification') {
		handler_type =
			auth === 'authorize'
				? 'Authorized_Server_Notification_Handler'
				: 'Public_Server_Notification_Handler';
	} else {
		// Local calls don't have server handlers
		return `${method}?: never`;
	}

	// Filter to only server-relevant phases
	const server_phases = phases.filter((phase: Action_Phase) => {
		switch (phase) {
			case 'receive_request':
			case 'receive':
				return true;
			case 'send_request':
			case 'send_response':
			case 'receive_response':
			case 'send':
			case 'execute':
				return false;
			default:
				throw new Unreachable_Error(phase);
		}
	});

	if (server_phases.length === 0) {
		return `${method}?: never`;
	}

	const phase_handlers = server_phases
		.map((phase: Action_Phase) => {
			if (kind === 'request_response') {
				collection_imports.add('Action_Inputs');
				collection_imports.add('Action_Outputs');
				return `${phase}?: ${handler_type}<
					Action_Inputs['${method}'],
					Action_Outputs['${method}']
				>`;
			} else {
				// Notifications don't have output
				collection_imports.add('Action_Inputs');
				return `${phase}?: ${handler_type}<
					Action_Inputs['${method}']
				>`;
			}
		})
		.join(';\n\t\t');

	return `${method}?: {\n\t\t${phase_handlers};\n\t}`;
};
