// generated by src/lib/server/server_action_types.gen.ts - DO NOT EDIT OR RISK LOST DATA

import type {z} from 'zod';

import type {
	Public_Server_Request_Handler,
	Public_Server_Notification_Handler,
} from '$lib/server/server_action_handler.js';
import type {
	create_directory_action_spec,
	delete_diskfile_action_spec,
	filer_change_action_spec,
	load_session_action_spec,
	ping_action_spec,
	submit_completion_action_spec,
	update_diskfile_action_spec,
} from '$lib/action_specs.js';

/**
 * Maps action methods to their server-side phase handlers.
 * Generated using ACTION_KIND_PHASES for consistent phase handling across all action kinds.
 */
export interface Server_Action_Handlers {
	create_directory?: {
		receive_request?: Public_Server_Request_Handler<
			z.infer<typeof create_directory_action_spec.input>,
			z.infer<typeof create_directory_action_spec.output>
		>;
	};
	delete_diskfile?: {
		receive_request?: Public_Server_Request_Handler<
			z.infer<typeof delete_diskfile_action_spec.input>,
			z.infer<typeof delete_diskfile_action_spec.output>
		>;
	};
	filer_change?: {
		receive?: Public_Server_Notification_Handler<z.infer<typeof filer_change_action_spec.input>>;
	};
	load_session?: {
		receive_request?: Public_Server_Request_Handler<
			z.infer<typeof load_session_action_spec.input>,
			z.infer<typeof load_session_action_spec.output>
		>;
	};
	ping?: {
		receive_request?: Public_Server_Request_Handler<
			z.infer<typeof ping_action_spec.input>,
			z.infer<typeof ping_action_spec.output>
		>;
	};
	submit_completion?: {
		receive_request?: Public_Server_Request_Handler<
			z.infer<typeof submit_completion_action_spec.input>,
			z.infer<typeof submit_completion_action_spec.output>
		>;
	};
	update_diskfile?: {
		receive_request?: Public_Server_Request_Handler<
			z.infer<typeof update_diskfile_action_spec.input>,
			z.infer<typeof update_diskfile_action_spec.output>
		>;
	};
}

// generated by src/lib/server/server_action_types.gen.ts - DO NOT EDIT OR RISK LOST DATA
